/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { ContaDreControllerCreateMutationRequest, ContaDreControllerCreateMutationResponse, ContaDreControllerCreateHeaderParams, ContaDreControllerCreate401, ContaDreControllerCreate404, ContaDreControllerCreate409 } from "../types/ContaDreControllerCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const contaDreControllerCreateMutationKey = () => [{ url: '/conta-dre' }] as const

export type ContaDreControllerCreateMutationKey = ReturnType<typeof contaDreControllerCreateMutationKey>

/**
 * @summary Criar nova conta DRE
 * {@link /conta-dre}
 */
export async function contaDreControllerCreate(data: ContaDreControllerCreateMutationRequest, headers: ContaDreControllerCreateHeaderParams, config: Partial<RequestConfig<ContaDreControllerCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ContaDreControllerCreateMutationResponse, ResponseErrorConfig<ContaDreControllerCreate401 | ContaDreControllerCreate404 | ContaDreControllerCreate409>, ContaDreControllerCreateMutationRequest>({ method : "POST", url : `/conta-dre`, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res.data
}

export function contaDreControllerCreateMutationOptions(config: Partial<RequestConfig<ContaDreControllerCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = contaDreControllerCreateMutationKey()
  return mutationOptions<ContaDreControllerCreateMutationResponse, ResponseErrorConfig<ContaDreControllerCreate401 | ContaDreControllerCreate404 | ContaDreControllerCreate409>, {data: ContaDreControllerCreateMutationRequest, headers: ContaDreControllerCreateHeaderParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data, headers }) => {
      return contaDreControllerCreate(data, headers, config)
    },
  })
}

/**
 * @summary Criar nova conta DRE
 * {@link /conta-dre}
 */
export function useContaDreControllerCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<ContaDreControllerCreateMutationResponse, ResponseErrorConfig<ContaDreControllerCreate401 | ContaDreControllerCreate404 | ContaDreControllerCreate409>, {data: ContaDreControllerCreateMutationRequest, headers: ContaDreControllerCreateHeaderParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ContaDreControllerCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? contaDreControllerCreateMutationKey()

  const baseOptions = contaDreControllerCreateMutationOptions(config) as UseMutationOptions<ContaDreControllerCreateMutationResponse, ResponseErrorConfig<ContaDreControllerCreate401 | ContaDreControllerCreate404 | ContaDreControllerCreate409>, {data: ContaDreControllerCreateMutationRequest, headers: ContaDreControllerCreateHeaderParams}, TContext>

  return useMutation<ContaDreControllerCreateMutationResponse, ResponseErrorConfig<ContaDreControllerCreate401 | ContaDreControllerCreate404 | ContaDreControllerCreate409>, {data: ContaDreControllerCreateMutationRequest, headers: ContaDreControllerCreateHeaderParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ContaDreControllerCreateMutationResponse, ResponseErrorConfig<ContaDreControllerCreate401 | ContaDreControllerCreate404 | ContaDreControllerCreate409>, {data: ContaDreControllerCreateMutationRequest, headers: ContaDreControllerCreateHeaderParams}, TContext>
}