/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/fetch-client'
import type {
  ClientesControllerFindByCanalOrigemQueryResponse,
  ClientesControllerFindByCanalOrigemPathParams,
} from '../types/ClientesControllerFindByCanalOrigem.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/fetch-client'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const clientesControllerFindByCanalOrigemSuspenseQueryKey = (canalOrigemId: ClientesControllerFindByCanalOrigemPathParams['canalOrigemId']) =>
  [{ url: '/clientes/canal-origem/:canalOrigemId', params: { canalOrigemId: canalOrigemId } }] as const

export type ClientesControllerFindByCanalOrigemSuspenseQueryKey = ReturnType<typeof clientesControllerFindByCanalOrigemSuspenseQueryKey>

/**
 * @summary Listar clientes por canal de origem
 * {@link /clientes/canal-origem/:canalOrigemId}
 */
export async function clientesControllerFindByCanalOrigemSuspense(
  canalOrigemId: ClientesControllerFindByCanalOrigemPathParams['canalOrigemId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<ClientesControllerFindByCanalOrigemQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/clientes/canal-origem/${canalOrigemId}`,
    ...requestConfig,
  })
  return res.data
}

export function clientesControllerFindByCanalOrigemSuspenseQueryOptions(
  canalOrigemId: ClientesControllerFindByCanalOrigemPathParams['canalOrigemId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = clientesControllerFindByCanalOrigemSuspenseQueryKey(canalOrigemId)
  return queryOptions<
    ClientesControllerFindByCanalOrigemQueryResponse,
    ResponseErrorConfig<Error>,
    ClientesControllerFindByCanalOrigemQueryResponse,
    typeof queryKey
  >({
    enabled: !!canalOrigemId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return clientesControllerFindByCanalOrigemSuspense(canalOrigemId, config)
    },
  })
}

/**
 * @summary Listar clientes por canal de origem
 * {@link /clientes/canal-origem/:canalOrigemId}
 */
export function useClientesControllerFindByCanalOrigemSuspense<
  TData = ClientesControllerFindByCanalOrigemQueryResponse,
  TQueryKey extends QueryKey = ClientesControllerFindByCanalOrigemSuspenseQueryKey,
>(
  canalOrigemId: ClientesControllerFindByCanalOrigemPathParams['canalOrigemId'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ClientesControllerFindByCanalOrigemQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? clientesControllerFindByCanalOrigemSuspenseQueryKey(canalOrigemId)

  const query = useSuspenseQuery(
    {
      ...clientesControllerFindByCanalOrigemSuspenseQueryOptions(canalOrigemId, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}