/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/fetch-client'
import type {
  ContasPagarControllerFindByParceiroQueryResponse,
  ContasPagarControllerFindByParceiroPathParams,
} from '../types/ContasPagarControllerFindByParceiro.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/fetch-client'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const contasPagarControllerFindByParceiroSuspenseQueryKey = (parceiroId: ContasPagarControllerFindByParceiroPathParams['parceiroId']) =>
  [{ url: '/contas-pagar/parceiro/:parceiroId', params: { parceiroId: parceiroId } }] as const

export type ContasPagarControllerFindByParceiroSuspenseQueryKey = ReturnType<typeof contasPagarControllerFindByParceiroSuspenseQueryKey>

/**
 * @summary Buscar contas a pagar por parceiro
 * {@link /contas-pagar/parceiro/:parceiroId}
 */
export async function contasPagarControllerFindByParceiroSuspense(
  parceiroId: ContasPagarControllerFindByParceiroPathParams['parceiroId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<ContasPagarControllerFindByParceiroQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/contas-pagar/parceiro/${parceiroId}`,
    ...requestConfig,
  })
  return res.data
}

export function contasPagarControllerFindByParceiroSuspenseQueryOptions(
  parceiroId: ContasPagarControllerFindByParceiroPathParams['parceiroId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = contasPagarControllerFindByParceiroSuspenseQueryKey(parceiroId)
  return queryOptions<
    ContasPagarControllerFindByParceiroQueryResponse,
    ResponseErrorConfig<Error>,
    ContasPagarControllerFindByParceiroQueryResponse,
    typeof queryKey
  >({
    enabled: !!parceiroId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return contasPagarControllerFindByParceiroSuspense(parceiroId, config)
    },
  })
}

/**
 * @summary Buscar contas a pagar por parceiro
 * {@link /contas-pagar/parceiro/:parceiroId}
 */
export function useContasPagarControllerFindByParceiroSuspense<
  TData = ContasPagarControllerFindByParceiroQueryResponse,
  TQueryKey extends QueryKey = ContasPagarControllerFindByParceiroSuspenseQueryKey,
>(
  parceiroId: ContasPagarControllerFindByParceiroPathParams['parceiroId'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ContasPagarControllerFindByParceiroQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? contasPagarControllerFindByParceiroSuspenseQueryKey(parceiroId)

  const query = useSuspenseQuery(
    {
      ...contasPagarControllerFindByParceiroSuspenseQueryOptions(parceiroId, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}