/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/fetch-client'
import type {
  ContasPagarControllerFindByParceiroQueryResponse,
  ContasPagarControllerFindByParceiroPathParams,
} from '../types/ContasPagarControllerFindByParceiro.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/fetch-client'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const contasPagarControllerFindByParceiroQueryKey = (parceiroId: ContasPagarControllerFindByParceiroPathParams['parceiroId']) =>
  [{ url: '/contas-pagar/parceiro/:parceiroId', params: { parceiroId: parceiroId } }] as const

export type ContasPagarControllerFindByParceiroQueryKey = ReturnType<typeof contasPagarControllerFindByParceiroQueryKey>

/**
 * @summary Buscar contas a pagar por parceiro
 * {@link /contas-pagar/parceiro/:parceiroId}
 */
export async function contasPagarControllerFindByParceiro(
  parceiroId: ContasPagarControllerFindByParceiroPathParams['parceiroId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<ContasPagarControllerFindByParceiroQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/contas-pagar/parceiro/${parceiroId}`,
    ...requestConfig,
  })
  return res.data
}

export function contasPagarControllerFindByParceiroQueryOptions(
  parceiroId: ContasPagarControllerFindByParceiroPathParams['parceiroId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = contasPagarControllerFindByParceiroQueryKey(parceiroId)
  return queryOptions<
    ContasPagarControllerFindByParceiroQueryResponse,
    ResponseErrorConfig<Error>,
    ContasPagarControllerFindByParceiroQueryResponse,
    typeof queryKey
  >({
    enabled: !!parceiroId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return contasPagarControllerFindByParceiro(parceiroId, config)
    },
  })
}

/**
 * @summary Buscar contas a pagar por parceiro
 * {@link /contas-pagar/parceiro/:parceiroId}
 */
export function useContasPagarControllerFindByParceiro<
  TData = ContasPagarControllerFindByParceiroQueryResponse,
  TQueryData = ContasPagarControllerFindByParceiroQueryResponse,
  TQueryKey extends QueryKey = ContasPagarControllerFindByParceiroQueryKey,
>(
  parceiroId: ContasPagarControllerFindByParceiroPathParams['parceiroId'],
  options: {
    query?: Partial<QueryObserverOptions<ContasPagarControllerFindByParceiroQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? contasPagarControllerFindByParceiroQueryKey(parceiroId)

  const query = useQuery(
    {
      ...contasPagarControllerFindByParceiroQueryOptions(parceiroId, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}