/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { ContasPagarParcelasControllerFindAllAgendaQueryResponse, ContasPagarParcelasControllerFindAllAgendaPathParams } from "../types/ContasPagarParcelasControllerFindAllAgenda.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const contasPagarParcelasControllerFindAllAgendaSuspenseQueryKey = (parceiroId: ContasPagarParcelasControllerFindAllAgendaPathParams["parceiroId"]) =>   [{ url: '/contas-pagar-parcelas/agenda/:parceiroId', params: {parceiroId:parceiroId} }] as const

export type ContasPagarParcelasControllerFindAllAgendaSuspenseQueryKey = ReturnType<typeof contasPagarParcelasControllerFindAllAgendaSuspenseQueryKey>

/**
 * @summary Listar todas as parcelas de contas a pagar da agenda de compromissos
 * {@link /contas-pagar-parcelas/agenda/:parceiroId}
 */
export async function contasPagarParcelasControllerFindAllAgendaSuspense(parceiroId: ContasPagarParcelasControllerFindAllAgendaPathParams["parceiroId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client:request = fetch, ...requestConfig } = config


const res = await request<ContasPagarParcelasControllerFindAllAgendaQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/contas-pagar-parcelas/agenda/${parceiroId}`, ... requestConfig })
return res.data
}

export function contasPagarParcelasControllerFindAllAgendaSuspenseQueryOptions(parceiroId: ContasPagarParcelasControllerFindAllAgendaPathParams["parceiroId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  
        const queryKey = contasPagarParcelasControllerFindAllAgendaSuspenseQueryKey(parceiroId)
        return queryOptions<ContasPagarParcelasControllerFindAllAgendaQueryResponse, ResponseErrorConfig<Error>, ContasPagarParcelasControllerFindAllAgendaQueryResponse, typeof queryKey>({
         enabled: !!(parceiroId),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return contasPagarParcelasControllerFindAllAgendaSuspense(parceiroId, config)
         },
        })
  
}

/**
 * @summary Listar todas as parcelas de contas a pagar da agenda de compromissos
 * {@link /contas-pagar-parcelas/agenda/:parceiroId}
 */
export function useContasPagarParcelasControllerFindAllAgendaSuspense<TData = ContasPagarParcelasControllerFindAllAgendaQueryResponse, TQueryKey extends QueryKey = ContasPagarParcelasControllerFindAllAgendaSuspenseQueryKey>(parceiroId: ContasPagarParcelasControllerFindAllAgendaPathParams["parceiroId"], options: 
  {
    query?: Partial<UseSuspenseQueryOptions<ContasPagarParcelasControllerFindAllAgendaQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  }
   = {}) {
  
         const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
         const queryKey = queryOptions?.queryKey ?? contasPagarParcelasControllerFindAllAgendaSuspenseQueryKey(parceiroId)
  
         const query = useSuspenseQuery({
          ...contasPagarParcelasControllerFindAllAgendaSuspenseQueryOptions(parceiroId, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }
  
         query.queryKey = queryKey as TQueryKey
  
         return query
         
}