/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/fetch-client'
import type { FornecedoresControllerFindAllQueryResponse } from '../types/FornecedoresControllerFindAll.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/fetch-client'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const fornecedoresControllerFindAllQueryKey = () => [{ url: '/fornecedores' }] as const

export type FornecedoresControllerFindAllQueryKey = ReturnType<typeof fornecedoresControllerFindAllQueryKey>

/**
 * @summary Listar todos os fornecedores
 * {@link /fornecedores}
 */
export async function fornecedoresControllerFindAll(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<FornecedoresControllerFindAllQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/fornecedores`,
    ...requestConfig,
  })
  return res.data
}

export function fornecedoresControllerFindAllQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = fornecedoresControllerFindAllQueryKey()
  return queryOptions<FornecedoresControllerFindAllQueryResponse, ResponseErrorConfig<Error>, FornecedoresControllerFindAllQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return fornecedoresControllerFindAll(config)
    },
  })
}

/**
 * @summary Listar todos os fornecedores
 * {@link /fornecedores}
 */
export function useFornecedoresControllerFindAll<
  TData = FornecedoresControllerFindAllQueryResponse,
  TQueryData = FornecedoresControllerFindAllQueryResponse,
  TQueryKey extends QueryKey = FornecedoresControllerFindAllQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<FornecedoresControllerFindAllQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? fornecedoresControllerFindAllQueryKey()

  const query = useQuery(
    {
      ...fornecedoresControllerFindAllQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}