/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { FornecedoresControllerFindAllQueryResponse, FornecedoresControllerFindAllHeaderParams, FornecedoresControllerFindAll400 } from "../types/FornecedoresControllerFindAll.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const fornecedoresControllerFindAllQueryKey = () =>   [{ url: '/fornecedores' }] as const

export type FornecedoresControllerFindAllQueryKey = ReturnType<typeof fornecedoresControllerFindAllQueryKey>

/**
 * @summary Listar todos os fornecedores de um parceiro
 * {@link /fornecedores}
 */
export async function fornecedoresControllerFindAll(headers: FornecedoresControllerFindAllHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client:request = fetch, ...requestConfig } = config


const res = await request<FornecedoresControllerFindAllQueryResponse, ResponseErrorConfig<FornecedoresControllerFindAll400>, unknown>({ method : "GET", url : `/fornecedores`, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })
return res.data
}

export function fornecedoresControllerFindAllQueryOptions(headers: FornecedoresControllerFindAllHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  
        const queryKey = fornecedoresControllerFindAllQueryKey()
        return queryOptions<FornecedoresControllerFindAllQueryResponse, ResponseErrorConfig<FornecedoresControllerFindAll400>, FornecedoresControllerFindAllQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return fornecedoresControllerFindAll(headers, config)
         },
        })
  
}

/**
 * @summary Listar todos os fornecedores de um parceiro
 * {@link /fornecedores}
 */
export function useFornecedoresControllerFindAll<TData = FornecedoresControllerFindAllQueryResponse, TQueryData = FornecedoresControllerFindAllQueryResponse, TQueryKey extends QueryKey = FornecedoresControllerFindAllQueryKey>(headers: FornecedoresControllerFindAllHeaderParams, options: 
  {
    query?: Partial<QueryObserverOptions<FornecedoresControllerFindAllQueryResponse, ResponseErrorConfig<FornecedoresControllerFindAll400>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  }
   = {}) {
  
         const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
         const queryKey = queryOptions?.queryKey ?? fornecedoresControllerFindAllQueryKey()
  
         const query = useQuery({
          ...fornecedoresControllerFindAllQueryOptions(headers, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<FornecedoresControllerFindAll400>> & { queryKey: TQueryKey }
  
         query.queryKey = queryKey as TQueryKey
  
         return query
         
}