/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { ImpostoControllerCreateMutationRequest, ImpostoControllerCreateMutationResponse, ImpostoControllerCreateHeaderParams, ImpostoControllerCreate401, ImpostoControllerCreate409 } from "../types/ImpostoControllerCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const impostoControllerCreateMutationKey = () => [{ url: '/imposto' }] as const

export type ImpostoControllerCreateMutationKey = ReturnType<typeof impostoControllerCreateMutationKey>

/**
 * @summary Criar novo imposto
 * {@link /imposto}
 */
export async function impostoControllerCreate(data: ImpostoControllerCreateMutationRequest, headers: ImpostoControllerCreateHeaderParams, config: Partial<RequestConfig<ImpostoControllerCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ImpostoControllerCreateMutationResponse, ResponseErrorConfig<ImpostoControllerCreate401 | ImpostoControllerCreate409>, ImpostoControllerCreateMutationRequest>({ method : "POST", url : `/imposto`, data : requestData, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res.data
}

export function impostoControllerCreateMutationOptions(config: Partial<RequestConfig<ImpostoControllerCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = impostoControllerCreateMutationKey()
  return mutationOptions<ImpostoControllerCreateMutationResponse, ResponseErrorConfig<ImpostoControllerCreate401 | ImpostoControllerCreate409>, {data: ImpostoControllerCreateMutationRequest, headers: ImpostoControllerCreateHeaderParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data, headers }) => {
      return impostoControllerCreate(data, headers, config)
    },
  })
}

/**
 * @summary Criar novo imposto
 * {@link /imposto}
 */
export function useImpostoControllerCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<ImpostoControllerCreateMutationResponse, ResponseErrorConfig<ImpostoControllerCreate401 | ImpostoControllerCreate409>, {data: ImpostoControllerCreateMutationRequest, headers: ImpostoControllerCreateHeaderParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ImpostoControllerCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? impostoControllerCreateMutationKey()

  const baseOptions = impostoControllerCreateMutationOptions(config) as UseMutationOptions<ImpostoControllerCreateMutationResponse, ResponseErrorConfig<ImpostoControllerCreate401 | ImpostoControllerCreate409>, {data: ImpostoControllerCreateMutationRequest, headers: ImpostoControllerCreateHeaderParams}, TContext>

  return useMutation<ImpostoControllerCreateMutationResponse, ResponseErrorConfig<ImpostoControllerCreate401 | ImpostoControllerCreate409>, {data: ImpostoControllerCreateMutationRequest, headers: ImpostoControllerCreateHeaderParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ImpostoControllerCreateMutationResponse, ResponseErrorConfig<ImpostoControllerCreate401 | ImpostoControllerCreate409>, {data: ImpostoControllerCreateMutationRequest, headers: ImpostoControllerCreateHeaderParams}, TContext>
}