/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { LancamentoDreControllerGetAnosDisponiveisQueryResponse } from "../types/LancamentoDreControllerGetAnosDisponiveis.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const lancamentoDreControllerGetAnosDisponiveisSuspenseQueryKey = () => [{ url: '/lancamento-dre/anos' }] as const

export type LancamentoDreControllerGetAnosDisponiveisSuspenseQueryKey = ReturnType<typeof lancamentoDreControllerGetAnosDisponiveisSuspenseQueryKey>

/**
 * @summary Lista anos disponíveis com lançamentos DRE
 * {@link /lancamento-dre/anos}
 */
export async function lancamentoDreControllerGetAnosDisponiveisSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<LancamentoDreControllerGetAnosDisponiveisQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/lancamento-dre/anos`, ... requestConfig })  
  return res.data
}

export function lancamentoDreControllerGetAnosDisponiveisSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = lancamentoDreControllerGetAnosDisponiveisSuspenseQueryKey()
  return queryOptions<LancamentoDreControllerGetAnosDisponiveisQueryResponse, ResponseErrorConfig<Error>, LancamentoDreControllerGetAnosDisponiveisQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return lancamentoDreControllerGetAnosDisponiveisSuspense(config)
   },
  })
}

/**
 * @summary Lista anos disponíveis com lançamentos DRE
 * {@link /lancamento-dre/anos}
 */
export function useLancamentoDreControllerGetAnosDisponiveisSuspense<TData = LancamentoDreControllerGetAnosDisponiveisQueryResponse, TQueryKey extends QueryKey = LancamentoDreControllerGetAnosDisponiveisSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<LancamentoDreControllerGetAnosDisponiveisQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? lancamentoDreControllerGetAnosDisponiveisSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...lancamentoDreControllerGetAnosDisponiveisSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}