/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { PagamentoControllerFindOneQueryResponse, PagamentoControllerFindOnePathParams, PagamentoControllerFindOneHeaderParams, PagamentoControllerFindOne404 } from "../types/PagamentoControllerFindOne.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const pagamentoControllerFindOneQueryKey = (id: PagamentoControllerFindOnePathParams["id"]) =>   [{ url: '/pagamento/:id', params: {id:id} }] as const

export type PagamentoControllerFindOneQueryKey = ReturnType<typeof pagamentoControllerFindOneQueryKey>

/**
 * @summary Buscar pagamento por ID
 * {@link /pagamento/:id}
 */
export async function pagamentoControllerFindOne(id: PagamentoControllerFindOnePathParams["id"], headers: PagamentoControllerFindOneHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client:request = fetch, ...requestConfig } = config


const res = await request<PagamentoControllerFindOneQueryResponse, ResponseErrorConfig<PagamentoControllerFindOne404>, unknown>({ method : "GET", url : `/pagamento/${id}`, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })
return res.data
}

export function pagamentoControllerFindOneQueryOptions(id: PagamentoControllerFindOnePathParams["id"], headers: PagamentoControllerFindOneHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  
        const queryKey = pagamentoControllerFindOneQueryKey(id)
        return queryOptions<PagamentoControllerFindOneQueryResponse, ResponseErrorConfig<PagamentoControllerFindOne404>, PagamentoControllerFindOneQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return pagamentoControllerFindOne(id, headers, config)
         },
        })
  
}

/**
 * @summary Buscar pagamento por ID
 * {@link /pagamento/:id}
 */
export function usePagamentoControllerFindOne<TData = PagamentoControllerFindOneQueryResponse, TQueryData = PagamentoControllerFindOneQueryResponse, TQueryKey extends QueryKey = PagamentoControllerFindOneQueryKey>(id: PagamentoControllerFindOnePathParams["id"], headers: PagamentoControllerFindOneHeaderParams, options: 
  {
    query?: Partial<QueryObserverOptions<PagamentoControllerFindOneQueryResponse, ResponseErrorConfig<PagamentoControllerFindOne404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  }
   = {}) {
  
         const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
         const queryKey = queryOptions?.queryKey ?? pagamentoControllerFindOneQueryKey(id)
  
         const query = useQuery({
          ...pagamentoControllerFindOneQueryOptions(id, headers, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<PagamentoControllerFindOne404>> & { queryKey: TQueryKey }
  
         query.queryKey = queryKey as TQueryKey
  
         return query
         
}