/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { ParceirosControllerActivateParceiroMutationResponse, ParceirosControllerActivateParceiroPathParams, ParceirosControllerActivateParceiro404 } from "../types/ParceirosControllerActivateParceiro.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const parceirosControllerActivateParceiroMutationKey = () =>   [{"url":"/parceiros/{publicId}/ativar"}] as const

export type ParceirosControllerActivateParceiroMutationKey = ReturnType<typeof parceirosControllerActivateParceiroMutationKey>

/**
 * @summary Ativar parceiro
 * {@link /parceiros/:publicId/ativar}
 */
export async function parceirosControllerActivateParceiro(publicId: ParceirosControllerActivateParceiroPathParams["publicId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client:request = fetch, ...requestConfig } = config


const res = await request<ParceirosControllerActivateParceiroMutationResponse, ResponseErrorConfig<ParceirosControllerActivateParceiro404>, unknown>({ method : "PATCH", url : `/parceiros/${publicId}/ativar`, ... requestConfig })
return res.data
}

/**
 * @summary Ativar parceiro
 * {@link /parceiros/:publicId/ativar}
 */
export function useParceirosControllerActivateParceiro<TContext>(options: 
  {
    mutation?: UseMutationOptions<ParceirosControllerActivateParceiroMutationResponse, ResponseErrorConfig<ParceirosControllerActivateParceiro404>, {publicId: ParceirosControllerActivateParceiroPathParams["publicId"]}, TContext> & { client?: QueryClient },
    client?: Partial<RequestConfig> & { client?: typeof fetch },
  }
   = {}) {
  
          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? parceirosControllerActivateParceiroMutationKey()
  
          return useMutation<ParceirosControllerActivateParceiroMutationResponse, ResponseErrorConfig<ParceirosControllerActivateParceiro404>, {publicId: ParceirosControllerActivateParceiroPathParams["publicId"]}, TContext>({
            mutationFn: async({ publicId }) => {
              return parceirosControllerActivateParceiro(publicId, config)
            },
            mutationKey,
            ...mutationOptions
          }, queryClient)
      
}