/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { RegraLancamentoControllerFindAllQueryResponse, RegraLancamentoControllerFindAllHeaderParams, RegraLancamentoControllerFindAll401 } from "../types/RegraLancamentoControllerFindAll.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const regraLancamentoControllerFindAllSuspenseQueryKey = () => [{ url: '/regra-lancamento' }] as const

export type RegraLancamentoControllerFindAllSuspenseQueryKey = ReturnType<typeof regraLancamentoControllerFindAllSuspenseQueryKey>

/**
 * @summary Listar todas as regras de lançamento do parceiro
 * {@link /regra-lancamento}
 */
export async function regraLancamentoControllerFindAllSuspense(headers: RegraLancamentoControllerFindAllHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<RegraLancamentoControllerFindAllQueryResponse, ResponseErrorConfig<RegraLancamentoControllerFindAll401>, unknown>({ method : "GET", url : `/regra-lancamento`, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res.data
}

export function regraLancamentoControllerFindAllSuspenseQueryOptions(headers: RegraLancamentoControllerFindAllHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = regraLancamentoControllerFindAllSuspenseQueryKey()
  return queryOptions<RegraLancamentoControllerFindAllQueryResponse, ResponseErrorConfig<RegraLancamentoControllerFindAll401>, RegraLancamentoControllerFindAllQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return regraLancamentoControllerFindAllSuspense(headers, config)
   },
  })
}

/**
 * @summary Listar todas as regras de lançamento do parceiro
 * {@link /regra-lancamento}
 */
export function useRegraLancamentoControllerFindAllSuspense<TData = RegraLancamentoControllerFindAllQueryResponse, TQueryKey extends QueryKey = RegraLancamentoControllerFindAllSuspenseQueryKey>(headers: RegraLancamentoControllerFindAllHeaderParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<RegraLancamentoControllerFindAllQueryResponse, ResponseErrorConfig<RegraLancamentoControllerFindAll401>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? regraLancamentoControllerFindAllSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...regraLancamentoControllerFindAllSuspenseQueryOptions(headers, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<RegraLancamentoControllerFindAll401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}