/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { RollupControllerGetSummaryQueryResponse, RollupControllerGetSummaryQueryParams } from "../types/RollupControllerGetSummary.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const rollupControllerGetSummarySuspenseQueryKey = (params: RollupControllerGetSummaryQueryParams) =>   [{ url: '/dashboard/despesas/mes' }, ...(params ? [params] : [])] as const

export type RollupControllerGetSummarySuspenseQueryKey = ReturnType<typeof rollupControllerGetSummarySuspenseQueryKey>

/**
 * @summary Obter resumo mensal de despesas
 * {@link /dashboard/despesas/mes}
 */
export async function rollupControllerGetSummarySuspense(params: RollupControllerGetSummaryQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client:request = fetch, ...requestConfig } = config


const res = await request<RollupControllerGetSummaryQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/dashboard/despesas/mes`, params, ... requestConfig })
return res.data
}

export function rollupControllerGetSummarySuspenseQueryOptions(params: RollupControllerGetSummaryQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  
        const queryKey = rollupControllerGetSummarySuspenseQueryKey(params)
        return queryOptions<RollupControllerGetSummaryQueryResponse, ResponseErrorConfig<Error>, RollupControllerGetSummaryQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return rollupControllerGetSummarySuspense(params, config)
         },
        })
  
}

/**
 * @summary Obter resumo mensal de despesas
 * {@link /dashboard/despesas/mes}
 */
export function useRollupControllerGetSummarySuspense<TData = RollupControllerGetSummaryQueryResponse, TQueryKey extends QueryKey = RollupControllerGetSummarySuspenseQueryKey>(params: RollupControllerGetSummaryQueryParams, options: 
  {
    query?: Partial<UseSuspenseQueryOptions<RollupControllerGetSummaryQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  }
   = {}) {
  
         const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
         const queryKey = queryOptions?.queryKey ?? rollupControllerGetSummarySuspenseQueryKey(params)
  
         const query = useSuspenseQuery({
          ...rollupControllerGetSummarySuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }
  
         query.queryKey = queryKey as TQueryKey
  
         return query
         
}