/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { TransferenciaEstoqueControllerFindOneQueryResponse, TransferenciaEstoqueControllerFindOnePathParams, TransferenciaEstoqueControllerFindOne404 } from "../types/TransferenciaEstoqueControllerFindOne.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const transferenciaEstoqueControllerFindOneQueryKey = (id: TransferenciaEstoqueControllerFindOnePathParams["id"]) =>   [{ url: '/transferencia-estoque/:id', params: {id:id} }] as const

export type TransferenciaEstoqueControllerFindOneQueryKey = ReturnType<typeof transferenciaEstoqueControllerFindOneQueryKey>

/**
 * @description Retorna uma transferência de estoque específica pelo seu ID, incluindo todos os itens e movimentos relacionados
 * @summary Buscar transferência por ID
 * {@link /transferencia-estoque/:id}
 */
export async function transferenciaEstoqueControllerFindOne(id: TransferenciaEstoqueControllerFindOnePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client:request = fetch, ...requestConfig } = config


const res = await request<TransferenciaEstoqueControllerFindOneQueryResponse, ResponseErrorConfig<TransferenciaEstoqueControllerFindOne404>, unknown>({ method : "GET", url : `/transferencia-estoque/${id}`, ... requestConfig })
return res.data
}

export function transferenciaEstoqueControllerFindOneQueryOptions(id: TransferenciaEstoqueControllerFindOnePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  
        const queryKey = transferenciaEstoqueControllerFindOneQueryKey(id)
        return queryOptions<TransferenciaEstoqueControllerFindOneQueryResponse, ResponseErrorConfig<TransferenciaEstoqueControllerFindOne404>, TransferenciaEstoqueControllerFindOneQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return transferenciaEstoqueControllerFindOne(id, config)
         },
        })
  
}

/**
 * @description Retorna uma transferência de estoque específica pelo seu ID, incluindo todos os itens e movimentos relacionados
 * @summary Buscar transferência por ID
 * {@link /transferencia-estoque/:id}
 */
export function useTransferenciaEstoqueControllerFindOne<TData = TransferenciaEstoqueControllerFindOneQueryResponse, TQueryData = TransferenciaEstoqueControllerFindOneQueryResponse, TQueryKey extends QueryKey = TransferenciaEstoqueControllerFindOneQueryKey>(id: TransferenciaEstoqueControllerFindOnePathParams["id"], options: 
  {
    query?: Partial<QueryObserverOptions<TransferenciaEstoqueControllerFindOneQueryResponse, ResponseErrorConfig<TransferenciaEstoqueControllerFindOne404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  }
   = {}) {
  
         const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
         const queryKey = queryOptions?.queryKey ?? transferenciaEstoqueControllerFindOneQueryKey(id)
  
         const query = useQuery({
          ...transferenciaEstoqueControllerFindOneQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<TransferenciaEstoqueControllerFindOne404>> & { queryKey: TQueryKey }
  
         query.queryKey = queryKey as TQueryKey
  
         return query
         
}