/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/fetch-client";
import type { VendaControllerConfirmarCondicionalMutationResponse, VendaControllerConfirmarCondicionalPathParams, VendaControllerConfirmarCondicionalHeaderParams } from "../types/VendaControllerConfirmarCondicional.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/fetch-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const vendaControllerConfirmarCondicionalMutationKey = () => [{ url: '/venda/:publicId/confirmarCondicional' }] as const

export type VendaControllerConfirmarCondicionalMutationKey = ReturnType<typeof vendaControllerConfirmarCondicionalMutationKey>

/**
 * @summary Confirmar envio de produtos em condicional (baixa estoque, NÃO gera pagamento)
 * {@link /venda/:publicId/confirmarCondicional}
 */
export async function vendaControllerConfirmarCondicional(publicId: VendaControllerConfirmarCondicionalPathParams["publicId"], headers: VendaControllerConfirmarCondicionalHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<VendaControllerConfirmarCondicionalMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "PATCH", url : `/venda/${publicId}/confirmarCondicional`, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res.data
}

export function vendaControllerConfirmarCondicionalMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = vendaControllerConfirmarCondicionalMutationKey()
  return mutationOptions<VendaControllerConfirmarCondicionalMutationResponse, ResponseErrorConfig<Error>, {publicId: VendaControllerConfirmarCondicionalPathParams["publicId"], headers: VendaControllerConfirmarCondicionalHeaderParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ publicId, headers }) => {
      return vendaControllerConfirmarCondicional(publicId, headers, config)
    },
  })
}

/**
 * @summary Confirmar envio de produtos em condicional (baixa estoque, NÃO gera pagamento)
 * {@link /venda/:publicId/confirmarCondicional}
 */
export function useVendaControllerConfirmarCondicional<TContext>(options: 
{
  mutation?: UseMutationOptions<VendaControllerConfirmarCondicionalMutationResponse, ResponseErrorConfig<Error>, {publicId: VendaControllerConfirmarCondicionalPathParams["publicId"], headers: VendaControllerConfirmarCondicionalHeaderParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? vendaControllerConfirmarCondicionalMutationKey()

  const baseOptions = vendaControllerConfirmarCondicionalMutationOptions(config) as UseMutationOptions<VendaControllerConfirmarCondicionalMutationResponse, ResponseErrorConfig<Error>, {publicId: VendaControllerConfirmarCondicionalPathParams["publicId"], headers: VendaControllerConfirmarCondicionalHeaderParams}, TContext>

  return useMutation<VendaControllerConfirmarCondicionalMutationResponse, ResponseErrorConfig<Error>, {publicId: VendaControllerConfirmarCondicionalPathParams["publicId"], headers: VendaControllerConfirmarCondicionalHeaderParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<VendaControllerConfirmarCondicionalMutationResponse, ResponseErrorConfig<Error>, {publicId: VendaControllerConfirmarCondicionalPathParams["publicId"], headers: VendaControllerConfirmarCondicionalHeaderParams}, TContext>
}