/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthControllerGetUserParceiros200, AuthControllerGetUserParceirosQueryResponse } from "../types/AuthControllerGetUserParceiros.ts";
import { userParceiroItemDtoSchema } from "./userParceiroItemDtoSchema.ts";
import { z } from "zod/v4";

/**
 * @description Lista de parceiros do usuário
 */
export const authControllerGetUserParceiros200Schema = z.array(userParceiroItemDtoSchema) as unknown as z.ZodType<AuthControllerGetUserParceiros200>

export const authControllerGetUserParceirosQueryResponseSchema = authControllerGetUserParceiros200Schema as unknown as z.ZodType<AuthControllerGetUserParceirosQueryResponse>