/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CanalOrigemControllerFindOnePathParams, CanalOrigemControllerFindOne200, CanalOrigemControllerFindOne404, CanalOrigemControllerFindOneQueryResponse } from "../types/CanalOrigemControllerFindOne.ts";
import { canalOrigemSchema } from "./canalOrigemSchema.ts";
import { z } from "zod/v4";

export const canalOrigemControllerFindOnePathParamsSchema = z.object({
    "publicId": z.string().describe("ID público do canal de origem")
    }) as unknown as z.ZodType<CanalOrigemControllerFindOnePathParams>

/**
 * @description Canal de origem encontrado
 */
export const canalOrigemControllerFindOne200Schema = canalOrigemSchema as unknown as z.ZodType<CanalOrigemControllerFindOne200>

/**
 * @description Canal de origem não encontrado
 */
export const canalOrigemControllerFindOne404Schema = z.unknown() as unknown as z.ZodType<CanalOrigemControllerFindOne404>

export const canalOrigemControllerFindOneQueryResponseSchema = canalOrigemControllerFindOne200Schema as unknown as z.ZodType<CanalOrigemControllerFindOneQueryResponse>