/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CategoriaProdutoControllerFindAll200, CategoriaProdutoControllerFindAllQueryResponse } from "../types/CategoriaProdutoControllerFindAll.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

/**
 * @description Lista de categorias de produto retornada com sucesso
 */
export const categoriaProdutoControllerFindAll200Schema = z.array(z.object({
      "id": z.coerce.number().optional(),
  "descricao": z.coerce.string().optional()
      })) as unknown as ToZod<CategoriaProdutoControllerFindAll200>

export const categoriaProdutoControllerFindAllQueryResponseSchema = z.lazy(() => categoriaProdutoControllerFindAll200Schema) as unknown as ToZod<CategoriaProdutoControllerFindAllQueryResponse>