/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CategoriaDespesasControllerFindAll200, CategoriaDespesasControllerFindAll401, CategoriaDespesasControllerFindAllQueryResponse } from "../types/CategoriaDespesasControllerFindAll.ts";
import { categoriaDespesasSchema } from "./categoriaDespesasSchema.ts";
import { z } from "zod/v4";

/**
 * @description Lista de categorias de despesas retornada com sucesso
 */
export const categoriaDespesasControllerFindAll200Schema = z.array(categoriaDespesasSchema) as unknown as z.ZodType<CategoriaDespesasControllerFindAll200>

/**
 * @description Não autorizado
 */
export const categoriaDespesasControllerFindAll401Schema = z.unknown() as unknown as z.ZodType<CategoriaDespesasControllerFindAll401>

export const categoriaDespesasControllerFindAllQueryResponseSchema = categoriaDespesasControllerFindAll200Schema as unknown as z.ZodType<CategoriaDespesasControllerFindAllQueryResponse>