/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CategoriaResponseDto } from "../types/CategoriaResponseDto.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const categoriaResponseDtoSchema = z.object({
      "id": z.coerce.number().describe("ID da categoria"),
  "descricao": z.coerce.string().describe("Descrição da categoria")
      }) as unknown as ToZod<CategoriaResponseDto>