/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConfirmarRecebimentoDto } from "../types/ConfirmarRecebimentoDto.ts";
import { z } from "zod/v4";

export const confirmarRecebimentoDtoSchema = z.object({
    "observacao": z.optional(z.coerce.string().describe("Observação sobre o recebimento"))
    }) as unknown as z.ZodType<ConfirmarRecebimentoDto>