/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConferenciaItemControllerCreate201, ConferenciaItemControllerCreate400, ConferenciaItemControllerCreate404, ConferenciaItemControllerCreate409, ConferenciaItemControllerCreateMutationRequest, ConferenciaItemControllerCreateMutationResponse } from "../types/ConferenciaItemControllerCreate.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { conferenciaItemResponseDtoSchema } from "./conferenciaItemResponseDtoSchema.ts";
import { createConferenciaItemDtoSchema } from "./createConferenciaItemDtoSchema.ts";
import { z } from "zod";

/**
 * @description Item de conferência criado com sucesso
 */
export const conferenciaItemControllerCreate201Schema = z.lazy(() => conferenciaItemResponseDtoSchema) as unknown as ToZod<ConferenciaItemControllerCreate201>

/**
 * @description Dados inválidos
 */
export const conferenciaItemControllerCreate400Schema = z.unknown() as unknown as ToZod<ConferenciaItemControllerCreate400>

/**
 * @description Conferência ou SKU não encontrado
 */
export const conferenciaItemControllerCreate404Schema = z.unknown() as unknown as ToZod<ConferenciaItemControllerCreate404>

/**
 * @description Já existe item para este SKU nesta conferência
 */
export const conferenciaItemControllerCreate409Schema = z.unknown() as unknown as ToZod<ConferenciaItemControllerCreate409>

export const conferenciaItemControllerCreateMutationRequestSchema = z.lazy(() => createConferenciaItemDtoSchema) as unknown as ToZod<ConferenciaItemControllerCreateMutationRequest>

export const conferenciaItemControllerCreateMutationResponseSchema = z.lazy(() => conferenciaItemControllerCreate201Schema) as unknown as ToZod<ConferenciaItemControllerCreateMutationResponse>