/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConferenciaEstoqueControllerFindPaginatedQueryParams, ConferenciaEstoqueControllerFindPaginatedHeaderParams, ConferenciaEstoqueControllerFindPaginated200, ConferenciaEstoqueControllerFindPaginatedQueryResponse } from "../types/ConferenciaEstoqueControllerFindPaginated.ts";
import { paginatedConferenciaEstoqueResponseDtoSchema } from "./paginatedConferenciaEstoqueResponseDtoSchema.ts";
import { z } from "zod/v4";

export const conferenciaEstoqueControllerFindPaginatedQueryParamsSchema = z.object({
    "page": z.optional(z.coerce.number().default(1).describe("Número da página")),
"limit": z.optional(z.coerce.number().default(20).describe("Número de itens por página")),
"search": z.optional(z.string().describe("Termo de busca")),
"status": z.optional(z.enum(["PENDENTE", "EM_ANDAMENTO", "CONCLUIDA", "FINALIZADA", "CANCELADA"]).describe("Filtrar por status")),
"localEstoqueId": z.optional(z.coerce.number().describe("ID do local de estoque"))
    }) as unknown as z.ZodType<ConferenciaEstoqueControllerFindPaginatedQueryParams>

export const conferenciaEstoqueControllerFindPaginatedHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<ConferenciaEstoqueControllerFindPaginatedHeaderParams>

/**
 * @description Lista paginada de conferências de estoque
 */
export const conferenciaEstoqueControllerFindPaginated200Schema = paginatedConferenciaEstoqueResponseDtoSchema as unknown as z.ZodType<ConferenciaEstoqueControllerFindPaginated200>

export const conferenciaEstoqueControllerFindPaginatedQueryResponseSchema = conferenciaEstoqueControllerFindPaginated200Schema as unknown as z.ZodType<ConferenciaEstoqueControllerFindPaginatedQueryResponse>