/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ContaDreControllerRemovePathParams, ContaDreControllerRemoveHeaderParams, ContaDreControllerRemove200, ContaDreControllerRemove401, ContaDreControllerRemove404, ContaDreControllerRemoveMutationResponse } from "../types/ContaDreControllerRemove.ts";
import { z } from "zod/v4";

export const contaDreControllerRemovePathParamsSchema = z.object({
    "id": z.coerce.number().describe("ID da conta DRE")
    }) as unknown as z.ZodType<ContaDreControllerRemovePathParams>

export const contaDreControllerRemoveHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<ContaDreControllerRemoveHeaderParams>

/**
 * @description Conta DRE removida com sucesso
 */
export const contaDreControllerRemove200Schema = z.unknown() as unknown as z.ZodType<ContaDreControllerRemove200>

/**
 * @description Não autorizado
 */
export const contaDreControllerRemove401Schema = z.unknown() as unknown as z.ZodType<ContaDreControllerRemove401>

/**
 * @description Conta DRE não encontrada
 */
export const contaDreControllerRemove404Schema = z.unknown() as unknown as z.ZodType<ContaDreControllerRemove404>

export const contaDreControllerRemoveMutationResponseSchema = contaDreControllerRemove200Schema as unknown as z.ZodType<ContaDreControllerRemoveMutationResponse>