/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ContaDRE } from "../types/ContaDRE.ts";
import { z } from "zod/v4";

export const contaDRESchema = z.object({
    "id": z.coerce.number().describe("ID interno da conta DRE"),
"publicId": z.coerce.string().describe("ID público (UUID) da conta DRE"),
"grupoId": z.coerce.number().describe("ID do grupo DRE"),
"parceiroId": z.coerce.number().describe("ID do parceiro"),
"codigo": z.optional(z.coerce.string().describe("Código contábil opcional")),
"nome": z.coerce.string().describe("Nome da conta DRE"),
"nomeV1": z.optional(z.coerce.string().describe("Nome original da V1 para mapeamento na migração")),
"ordem": z.coerce.number().describe("Ordem de exibição dentro do grupo"),
"ativo": z.boolean().default(true).describe("Status ativo da conta"),
"createdAt": z.string().datetime().describe("Data de criação da conta")
    }) as unknown as z.ZodType<ContaDRE>