/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContasPagarParcelas } from '../types/ContasPagarParcelas.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { contasPagarSchema } from './contasPagarSchema.ts'
import { z } from 'zod'

export const contasPagarParcelasSchema = z.object({
  id: z.coerce.number().describe('ID único da parcela'),
  publicId: z.coerce.string().describe('ID público da parcela'),
  dataPagamento: z.string().datetime().describe('Data do pagamento da parcela'),
  dataVencimento: z.string().datetime().describe('Data de vencimento da parcela'),
  valor: z.coerce.number().describe('Valor da parcela'),
  pago: z.boolean().describe('Indica se a parcela foi paga'),
  contasPagarId: z.coerce.number().describe('ID da conta a pagar relacionada'),
  contasPagar: z
    .lazy(() => contasPagarSchema)
    .describe('Conta a pagar relacionada')
    .optional(),
}) as unknown as ToZod<ContasPagarParcelas>
