/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ContaDreControllerFindByGrupoPathParams, ContaDreControllerFindByGrupoHeaderParams, ContaDreControllerFindByGrupo200, ContaDreControllerFindByGrupo401, ContaDreControllerFindByGrupoQueryResponse } from "../types/ContaDreControllerFindByGrupo.ts";
import { contaDRESchema } from "./contaDRESchema.ts";
import { z } from "zod/v4";

export const contaDreControllerFindByGrupoPathParamsSchema = z.object({
    "grupoId": z.coerce.number().describe("ID do grupo DRE")
    }) as unknown as z.ZodType<ContaDreControllerFindByGrupoPathParams>

export const contaDreControllerFindByGrupoHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<ContaDreControllerFindByGrupoHeaderParams>

/**
 * @description Lista de contas DRE do grupo retornada com sucesso
 */
export const contaDreControllerFindByGrupo200Schema = z.array(contaDRESchema) as unknown as z.ZodType<ContaDreControllerFindByGrupo200>

/**
 * @description Não autorizado
 */
export const contaDreControllerFindByGrupo401Schema = z.unknown() as unknown as z.ZodType<ContaDreControllerFindByGrupo401>

export const contaDreControllerFindByGrupoQueryResponseSchema = contaDreControllerFindByGrupo200Schema as unknown as z.ZodType<ContaDreControllerFindByGrupoQueryResponse>