/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateContasPagarDto } from "../types/CreateContasPagarDto.ts";
import { z } from "zod/v4";

export const createContasPagarDtoSchema = z.object({
    "despesaId": z.optional(z.coerce.number().describe("ID da despesa relacionada")),
"valorTotal": z.coerce.number().describe("Valor total da conta a pagar"),
"saldo": z.optional(z.coerce.number().describe("Saldo atual da conta (soma dos valores pagos)")),
"pago": z.optional(z.boolean().describe("Indica se a conta foi totalmente paga")),
"dataPagamento": z.optional(z.coerce.string().describe("Data do pagamento da conta"))
    }) as unknown as z.ZodType<CreateContasPagarDto>