/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateProdutoDto } from "../types/CreateProdutoDto.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const createProdutoDtoSchema = z.object({
      "nome": z.coerce.string().max(255).describe("Nome do produto"),
  "descricao": z.coerce.string().describe("Descrição do produto").optional(),
  "imgURL": z.coerce.string().describe("URL da imagem do produto").optional(),
  "precoCompra": z.coerce.number().describe("Preço de compra do produto"),
  "precoVenda": z.coerce.number().describe("Preço de venda do produto"),
  "consignado": z.boolean().default(false).describe("Se o produto é consignado"),
  "categoriaId": z.coerce.number().describe("ID da categoria do produto").optional(),
  "ativo": z.boolean().default(true).describe("Status ativo do produto")
      }) as unknown as ToZod<CreateProdutoDto>