/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUsuarioDto } from "../types/CreateUsuarioDto.ts";
import { z } from "zod/v4";

export const createUsuarioDtoSchema = z.object({
    "nome": z.coerce.string().min(2).max(100).describe("Nome completo do usuário"),
"email": z.coerce.string().describe("Email do usuário"),
"telefone": z.optional(z.coerce.string().describe("Telefone do usuário para SMS ou WhatsApp")),
"provider": z.optional(z.coerce.string().default("LOCAL").describe("Provedor de autenticação")),
"googleId": z.optional(z.coerce.string().describe("ID do Google para autenticação OAuth")),
"senha": z.optional(z.coerce.string().min(6).describe("Senha do usuário")),
"ativo": z.optional(z.boolean().default(true).describe("Status ativo do usuário")),
"avatar": z.optional(z.coerce.string().describe("URL do avatar do usuário"))
    }) as unknown as z.ZodType<CreateUsuarioDto>