/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateContasPagarParcelasDto } from '../types/CreateContasPagarParcelasDto.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'

export const createContasPagarParcelasDtoSchema = z.object({
  dataPagamento: z.coerce.string().describe('Data do pagamento da parcela'),
  dataVencimento: z.coerce.string().describe('Data de vencimento da parcela'),
  valor: z.coerce.number().describe('Valor da parcela'),
  pago: z.boolean().describe('Se a parcela foi paga').optional(),
  contasPagarId: z.coerce.number().describe('ID da conta a pagar relacionada'),
}) as unknown as ToZod<CreateContasPagarParcelasDto>
