/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateCategoriaDespesasDto } from "../types/CreateCategoriaDespesasDto.ts";
import { z } from "zod/v4";

export const createCategoriaDespesasDtoSchema = z.object({
    "idCategoria": z.optional(z.coerce.number().describe("ID da categoria")),
"descricao": z.coerce.string().describe("Descrição da categoria de despesa"),
"ativo": z.optional(z.boolean().describe("Status ativo da categoria"))
    }) as unknown as z.ZodType<CreateCategoriaDespesasDto>