/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateSubCategoriaDespesaDto } from "../types/CreateSubCategoriaDespesaDto.ts";
import { z } from "zod/v4";

export const createSubCategoriaDespesaDtoSchema = z.object({
    "idSubCategoria": z.coerce.number().describe("ID da subcategoria de despesa").nullish(),
"categoriaId": z.coerce.number().describe("ID da categoria de despesa"),
"descricao": z.coerce.string().describe("Descrição da subcategoria de despesa"),
"ativo": z.boolean().describe("Status ativo da subcategoria").nullish()
    }) as unknown as z.ZodType<CreateSubCategoriaDespesaDto>