/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CurrencyControllerFindAllQueryParams, CurrencyControllerFindAll200, CurrencyControllerFindAll401, CurrencyControllerFindAllQueryResponse } from "../types/CurrencyControllerFindAll.ts";
import { currencySchema } from "./currencySchema.ts";
import { z } from "zod/v4";

export const currencyControllerFindAllQueryParamsSchema = z.object({
    "ativo": z.optional(z.boolean().describe("Filtrar por status ativo"))
    }).optional() as unknown as z.ZodType<CurrencyControllerFindAllQueryParams>

/**
 * @description Lista de moedas retornada com sucesso
 */
export const currencyControllerFindAll200Schema = z.array(currencySchema) as unknown as z.ZodType<CurrencyControllerFindAll200>

/**
 * @description Não autorizado
 */
export const currencyControllerFindAll401Schema = z.unknown() as unknown as z.ZodType<CurrencyControllerFindAll401>

export const currencyControllerFindAllQueryResponseSchema = currencyControllerFindAll200Schema as unknown as z.ZodType<CurrencyControllerFindAllQueryResponse>