/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CurrencyResponseDto } from "../types/CurrencyResponseDto.ts";
import { z } from "zod/v4";

export const currencyResponseDtoSchema = z.object({
    "id": z.coerce.number().describe("ID da moeda"),
"publicId": z.coerce.string().describe("ID público da moeda"),
"nome": z.coerce.string().describe("Nome da moeda"),
"prefixo": z.coerce.string().describe("Prefixo da moeda"),
"isoCode": z.coerce.string().describe("Código ISO da moeda")
    }) as unknown as z.ZodType<CurrencyResponseDto>