/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DespesasRecorrentesControllerFindOnePathParams, DespesasRecorrentesControllerFindOne200, DespesasRecorrentesControllerFindOne401, DespesasRecorrentesControllerFindOne404, DespesasRecorrentesControllerFindOneQueryResponse } from "../types/DespesasRecorrentesControllerFindOne.ts";
import { despesaRecorrenteSchema } from "./despesaRecorrenteSchema.ts";
import { z } from "zod/v4";

export const despesasRecorrentesControllerFindOnePathParamsSchema = z.object({
    "publicId": z.string().describe("ID público da despesa recorrente")
    }) as unknown as z.ZodType<DespesasRecorrentesControllerFindOnePathParams>

/**
 * @description Despesa recorrente encontrada
 */
export const despesasRecorrentesControllerFindOne200Schema = despesaRecorrenteSchema as unknown as z.ZodType<DespesasRecorrentesControllerFindOne200>

/**
 * @description Não autorizado
 */
export const despesasRecorrentesControllerFindOne401Schema = z.unknown() as unknown as z.ZodType<DespesasRecorrentesControllerFindOne401>

/**
 * @description Despesa recorrente não encontrada
 */
export const despesasRecorrentesControllerFindOne404Schema = z.unknown() as unknown as z.ZodType<DespesasRecorrentesControllerFindOne404>

export const despesasRecorrentesControllerFindOneQueryResponseSchema = despesasRecorrentesControllerFindOne200Schema as unknown as z.ZodType<DespesasRecorrentesControllerFindOneQueryResponse>