/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DespesasRecorrentesControllerUpdatePathParams, DespesasRecorrentesControllerUpdate200, DespesasRecorrentesControllerUpdate400, DespesasRecorrentesControllerUpdate401, DespesasRecorrentesControllerUpdate404, DespesasRecorrentesControllerUpdateMutationRequest, DespesasRecorrentesControllerUpdateMutationResponse } from "../types/DespesasRecorrentesControllerUpdate.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { despesaRecorrenteSchema } from "./despesaRecorrenteSchema.ts";
import { updateDespesaRecorrenteDtoSchema } from "./updateDespesaRecorrenteDtoSchema.ts";
import { z } from "zod";

export const despesasRecorrentesControllerUpdatePathParamsSchema = z.object({
      "publicId": z.string().describe("ID público da despesa recorrente")
      }) as unknown as ToZod<DespesasRecorrentesControllerUpdatePathParams>

/**
 * @description Despesa recorrente atualizada com sucesso
 */
export const despesasRecorrentesControllerUpdate200Schema = z.lazy(() => despesaRecorrenteSchema) as unknown as ToZod<DespesasRecorrentesControllerUpdate200>

/**
 * @description Dados inválidos
 */
export const despesasRecorrentesControllerUpdate400Schema = z.unknown() as unknown as ToZod<DespesasRecorrentesControllerUpdate400>

/**
 * @description Não autorizado
 */
export const despesasRecorrentesControllerUpdate401Schema = z.unknown() as unknown as ToZod<DespesasRecorrentesControllerUpdate401>

/**
 * @description Despesa recorrente não encontrada
 */
export const despesasRecorrentesControllerUpdate404Schema = z.unknown() as unknown as ToZod<DespesasRecorrentesControllerUpdate404>

export const despesasRecorrentesControllerUpdateMutationRequestSchema = z.lazy(() => updateDespesaRecorrenteDtoSchema) as unknown as ToZod<DespesasRecorrentesControllerUpdateMutationRequest>

export const despesasRecorrentesControllerUpdateMutationResponseSchema = z.lazy(() => despesasRecorrentesControllerUpdate200Schema) as unknown as ToZod<DespesasRecorrentesControllerUpdateMutationResponse>