/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DespesasControllerUpdatePathParams,
  DespesasControllerUpdateHeaderParams,
  DespesasControllerUpdate200,
  DespesasControllerUpdate400,
  DespesasControllerUpdate404,
  DespesasControllerUpdateMutationRequest,
  DespesasControllerUpdateMutationResponse,
} from '../types/DespesasControllerUpdate.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { despesaSchema } from './despesaSchema.ts'
import { updateDespesaDtoSchema } from './updateDespesaDtoSchema.ts'
import { z } from 'zod'

export const despesasControllerUpdatePathParamsSchema = z.object({
  publicId: z.string().describe('ID público da despesa'),
}) as unknown as ToZod<DespesasControllerUpdatePathParams>

export const despesasControllerUpdateHeaderParamsSchema = z.object({
  'x-parceiro-id': z.coerce.number().int().describe('ID do parceiro logado'),
}) as unknown as ToZod<DespesasControllerUpdateHeaderParams>

/**
 * @description Despesa atualizada com sucesso
 */
export const despesasControllerUpdate200Schema = z.lazy(() => despesaSchema) as unknown as ToZod<DespesasControllerUpdate200>

/**
 * @description Dados inválidos
 */
export const despesasControllerUpdate400Schema = z.unknown() as unknown as ToZod<DespesasControllerUpdate400>

/**
 * @description Despesa não encontrada
 */
export const despesasControllerUpdate404Schema = z.unknown() as unknown as ToZod<DespesasControllerUpdate404>

export const despesasControllerUpdateMutationRequestSchema = z.lazy(() => updateDespesaDtoSchema) as unknown as ToZod<DespesasControllerUpdateMutationRequest>

export const despesasControllerUpdateMutationResponseSchema = z.lazy(
  () => despesasControllerUpdate200Schema,
) as unknown as ToZod<DespesasControllerUpdateMutationResponse>