/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DespesasControllerRemovePathParams, DespesasControllerRemoveHeaderParams, DespesasControllerRemove204, DespesasControllerRemove404, DespesasControllerRemoveMutationResponse } from "../types/DespesasControllerRemove.ts";
import { z } from "zod/v4";

export const despesasControllerRemovePathParamsSchema = z.object({
    "publicId": z.string().describe("ID público da despesa")
    }) as unknown as z.ZodType<DespesasControllerRemovePathParams>

export const despesasControllerRemoveHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<DespesasControllerRemoveHeaderParams>

/**
 * @description Despesa removida com sucesso
 */
export const despesasControllerRemove204Schema = z.unknown() as unknown as z.ZodType<DespesasControllerRemove204>

/**
 * @description Despesa não encontrada
 */
export const despesasControllerRemove404Schema = z.unknown() as unknown as z.ZodType<DespesasControllerRemove404>

export const despesasControllerRemoveMutationResponseSchema = despesasControllerRemove204Schema as unknown as z.ZodType<DespesasControllerRemoveMutationResponse>