/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DespesasRecorrentesControllerUpdatePathParams, DespesasRecorrentesControllerUpdate200, DespesasRecorrentesControllerUpdate400, DespesasRecorrentesControllerUpdate401, DespesasRecorrentesControllerUpdate404, DespesasRecorrentesControllerUpdateMutationRequest, DespesasRecorrentesControllerUpdateMutationResponse } from "../types/DespesasRecorrentesControllerUpdate.ts";
import { despesaRecorrenteSchema } from "./despesaRecorrenteSchema.ts";
import { updateDespesaRecorrenteDtoSchema } from "./updateDespesaRecorrenteDtoSchema.ts";
import { z } from "zod/v4";

export const despesasRecorrentesControllerUpdatePathParamsSchema = z.object({
    "publicId": z.string().describe("ID público da despesa recorrente")
    }) as unknown as z.ZodType<DespesasRecorrentesControllerUpdatePathParams>

/**
 * @description Despesa recorrente atualizada com sucesso
 */
export const despesasRecorrentesControllerUpdate200Schema = despesaRecorrenteSchema as unknown as z.ZodType<DespesasRecorrentesControllerUpdate200>

/**
 * @description Dados inválidos
 */
export const despesasRecorrentesControllerUpdate400Schema = z.unknown() as unknown as z.ZodType<DespesasRecorrentesControllerUpdate400>

/**
 * @description Não autorizado
 */
export const despesasRecorrentesControllerUpdate401Schema = z.unknown() as unknown as z.ZodType<DespesasRecorrentesControllerUpdate401>

/**
 * @description Despesa recorrente não encontrada
 */
export const despesasRecorrentesControllerUpdate404Schema = z.unknown() as unknown as z.ZodType<DespesasRecorrentesControllerUpdate404>

export const despesasRecorrentesControllerUpdateMutationRequestSchema = updateDespesaRecorrenteDtoSchema as unknown as z.ZodType<DespesasRecorrentesControllerUpdateMutationRequest>

export const despesasRecorrentesControllerUpdateMutationResponseSchema = despesasRecorrentesControllerUpdate200Schema as unknown as z.ZodType<DespesasRecorrentesControllerUpdateMutationResponse>