/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EstoqueSkuControllerFindAll200, EstoqueSkuControllerFindAllQueryResponse } from "../types/EstoqueSkuControllerFindAll.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { estoqueSkuSchema } from "./estoqueSkuSchema.ts";
import { z } from "zod";

/**
 * @description Lista de registros de estoque retornada com sucesso
 */
export const estoqueSkuControllerFindAll200Schema = z.array(z.lazy(() => estoqueSkuSchema)) as unknown as ToZod<EstoqueSkuControllerFindAll200>

export const estoqueSkuControllerFindAllQueryResponseSchema = z.lazy(() => estoqueSkuControllerFindAll200Schema) as unknown as ToZod<EstoqueSkuControllerFindAllQueryResponse>