/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EstoqueSkuControllerFindByLocalPathParams, EstoqueSkuControllerFindByLocal200, EstoqueSkuControllerFindByLocalQueryResponse } from "../types/EstoqueSkuControllerFindByLocal.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { estoqueSkuSchema } from "./estoqueSkuSchema.ts";
import { z } from "zod";

export const estoqueSkuControllerFindByLocalPathParamsSchema = z.object({
      "localId": z.coerce.number().describe("ID do local de estoque")
      }) as unknown as ToZod<EstoqueSkuControllerFindByLocalPathParams>

/**
 * @description Lista de estoque do local retornada com sucesso
 */
export const estoqueSkuControllerFindByLocal200Schema = z.array(z.lazy(() => estoqueSkuSchema)) as unknown as ToZod<EstoqueSkuControllerFindByLocal200>

export const estoqueSkuControllerFindByLocalQueryResponseSchema = z.lazy(() => estoqueSkuControllerFindByLocal200Schema) as unknown as ToZod<EstoqueSkuControllerFindByLocalQueryResponse>