/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FornecedoresControllerFindAll200, FornecedoresControllerFindAllQueryResponse } from '../types/FornecedoresControllerFindAll.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { fornecedorSchema } from './fornecedorSchema.ts'
import { z } from 'zod'

/**
 * @description Lista de fornecedores retornada com sucesso
 */
export const fornecedoresControllerFindAll200Schema = z.array(z.lazy(() => fornecedorSchema)) as unknown as ToZod<FornecedoresControllerFindAll200>

export const fornecedoresControllerFindAllQueryResponseSchema = z.lazy(
  () => fornecedoresControllerFindAll200Schema,
) as unknown as ToZod<FornecedoresControllerFindAllQueryResponse>