/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  FornecedoresControllerFindActiveFornecedores200,
  FornecedoresControllerFindActiveFornecedoresQueryResponse,
} from '../types/FornecedoresControllerFindActiveFornecedores.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { fornecedorSchema } from './fornecedorSchema.ts'
import { z } from 'zod'

/**
 * @description Lista de fornecedores ativos retornada com sucesso
 */
export const fornecedoresControllerFindActiveFornecedores200Schema = z.array(
  z.lazy(() => fornecedorSchema),
) as unknown as ToZod<FornecedoresControllerFindActiveFornecedores200>

export const fornecedoresControllerFindActiveFornecedoresQueryResponseSchema = z.lazy(
  () => fornecedoresControllerFindActiveFornecedores200Schema,
) as unknown as ToZod<FornecedoresControllerFindActiveFornecedoresQueryResponse>