/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  FornecedoresControllerUpdateUltimaCompraPathParams,
  FornecedoresControllerUpdateUltimaCompra200,
  FornecedoresControllerUpdateUltimaCompra404,
  FornecedoresControllerUpdateUltimaCompraMutationResponse,
} from '../types/FornecedoresControllerUpdateUltimaCompra.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { fornecedorSchema } from './fornecedorSchema.ts'
import { z } from 'zod'

export const fornecedoresControllerUpdateUltimaCompraPathParamsSchema = z.object({
  publicId: z.string().describe('ID público do fornecedor (UUID v7)'),
}) as unknown as ToZod<FornecedoresControllerUpdateUltimaCompraPathParams>

/**
 * @description Data da última compra atualizada com sucesso
 */
export const fornecedoresControllerUpdateUltimaCompra200Schema = z.lazy(() => fornecedorSchema) as unknown as ToZod<FornecedoresControllerUpdateUltimaCompra200>

/**
 * @description Fornecedor não encontrado
 */
export const fornecedoresControllerUpdateUltimaCompra404Schema = z.unknown() as unknown as ToZod<FornecedoresControllerUpdateUltimaCompra404>

export const fornecedoresControllerUpdateUltimaCompraMutationResponseSchema = z.lazy(
  () => fornecedoresControllerUpdateUltimaCompra200Schema,
) as unknown as ToZod<FornecedoresControllerUpdateUltimaCompraMutationResponse>
