/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GrupoDreControllerFindAll200, GrupoDreControllerFindAll401, GrupoDreControllerFindAllQueryResponse } from "../types/GrupoDreControllerFindAll.ts";
import { grupoDRESchema } from "./grupoDRESchema.ts";
import { z } from "zod/v4";

/**
 * @description Lista de grupos DRE retornada com sucesso
 */
export const grupoDreControllerFindAll200Schema = z.array(grupoDRESchema) as unknown as z.ZodType<GrupoDreControllerFindAll200>

/**
 * @description Não autorizado
 */
export const grupoDreControllerFindAll401Schema = z.unknown() as unknown as z.ZodType<GrupoDreControllerFindAll401>

export const grupoDreControllerFindAllQueryResponseSchema = grupoDreControllerFindAll200Schema as unknown as z.ZodType<GrupoDreControllerFindAllQueryResponse>