/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ImpostoControllerCreateHeaderParams, ImpostoControllerCreate201, ImpostoControllerCreate401, ImpostoControllerCreate409, ImpostoControllerCreateMutationRequest, ImpostoControllerCreateMutationResponse } from "../types/ImpostoControllerCreate.ts";
import { createImpostoDtoSchema } from "./createImpostoDtoSchema.ts";
import { impostoSchema } from "./impostoSchema.ts";
import { z } from "zod/v4";

export const impostoControllerCreateHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<ImpostoControllerCreateHeaderParams>

/**
 * @description Imposto criado com sucesso
 */
export const impostoControllerCreate201Schema = impostoSchema as unknown as z.ZodType<ImpostoControllerCreate201>

/**
 * @description Não autorizado
 */
export const impostoControllerCreate401Schema = z.unknown() as unknown as z.ZodType<ImpostoControllerCreate401>

/**
 * @description Já existe um imposto com esta sigla para este parceiro
 */
export const impostoControllerCreate409Schema = z.unknown() as unknown as z.ZodType<ImpostoControllerCreate409>

export const impostoControllerCreateMutationRequestSchema = createImpostoDtoSchema as unknown as z.ZodType<ImpostoControllerCreateMutationRequest>

export const impostoControllerCreateMutationResponseSchema = impostoControllerCreate201Schema as unknown as z.ZodType<ImpostoControllerCreateMutationResponse>