/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ImpostoControllerUpdatePathParams, ImpostoControllerUpdateHeaderParams, ImpostoControllerUpdate200, ImpostoControllerUpdate401, ImpostoControllerUpdate404, ImpostoControllerUpdate409, ImpostoControllerUpdateMutationRequest, ImpostoControllerUpdateMutationResponse } from "../types/ImpostoControllerUpdate.ts";
import { impostoSchema } from "./impostoSchema.ts";
import { updateImpostoDtoSchema } from "./updateImpostoDtoSchema.ts";
import { z } from "zod/v4";

export const impostoControllerUpdatePathParamsSchema = z.object({
    "id": z.coerce.number().describe("ID do imposto")
    }) as unknown as z.ZodType<ImpostoControllerUpdatePathParams>

export const impostoControllerUpdateHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<ImpostoControllerUpdateHeaderParams>

/**
 * @description Imposto atualizado com sucesso
 */
export const impostoControllerUpdate200Schema = impostoSchema as unknown as z.ZodType<ImpostoControllerUpdate200>

/**
 * @description Não autorizado
 */
export const impostoControllerUpdate401Schema = z.unknown() as unknown as z.ZodType<ImpostoControllerUpdate401>

/**
 * @description Imposto não encontrado
 */
export const impostoControllerUpdate404Schema = z.unknown() as unknown as z.ZodType<ImpostoControllerUpdate404>

/**
 * @description Já existe um imposto com esta sigla para este parceiro
 */
export const impostoControllerUpdate409Schema = z.unknown() as unknown as z.ZodType<ImpostoControllerUpdate409>

export const impostoControllerUpdateMutationRequestSchema = updateImpostoDtoSchema as unknown as z.ZodType<ImpostoControllerUpdateMutationRequest>

export const impostoControllerUpdateMutationResponseSchema = impostoControllerUpdate200Schema as unknown as z.ZodType<ImpostoControllerUpdateMutationResponse>