/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LancamentoDreControllerGetLancamentosQueryParams, LancamentoDreControllerGetLancamentos200, LancamentoDreControllerGetLancamentosQueryResponse } from "../types/LancamentoDreControllerGetLancamentos.ts";
import { z } from "zod/v4";

export const lancamentoDreControllerGetLancamentosQueryParamsSchema = z.object({
    "dataInicio": z.string(),
"dataFim": z.string()
    }) as unknown as z.ZodType<LancamentoDreControllerGetLancamentosQueryParams>

export const lancamentoDreControllerGetLancamentos200Schema = z.unknown() as unknown as z.ZodType<LancamentoDreControllerGetLancamentos200>

export const lancamentoDreControllerGetLancamentosQueryResponseSchema = lancamentoDreControllerGetLancamentos200Schema as unknown as z.ZodType<LancamentoDreControllerGetLancamentosQueryResponse>