/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LocalEstoqueResponseDto } from "../types/LocalEstoqueResponseDto.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const localEstoqueResponseDtoSchema = z.object({
      "id": z.coerce.number().describe("ID do local"),
  "publicId": z.coerce.string().describe("Public ID do local"),
  "nome": z.coerce.string().describe("Nome do local"),
  "descricao": z.coerce.string().describe("Descrição do local")
      }) as unknown as ToZod<LocalEstoqueResponseDto>