/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LocalEstoqueControllerUpdatePathParams, LocalEstoqueControllerUpdate200, LocalEstoqueControllerUpdate404, LocalEstoqueControllerUpdate409, LocalEstoqueControllerUpdateMutationRequest, LocalEstoqueControllerUpdateMutationResponse } from "../types/LocalEstoqueControllerUpdate.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { localEstoqueSchema } from "./localEstoqueSchema.ts";
import { updateLocalEstoqueDtoSchema } from "./updateLocalEstoqueDtoSchema.ts";
import { z } from "zod";

export const localEstoqueControllerUpdatePathParamsSchema = z.object({
      "publicId": z.string().describe("ID público do local de estoque (UUID v7)")
      }) as unknown as ToZod<LocalEstoqueControllerUpdatePathParams>

/**
 * @description Local de estoque atualizado com sucesso
 */
export const localEstoqueControllerUpdate200Schema = z.lazy(() => localEstoqueSchema) as unknown as ToZod<LocalEstoqueControllerUpdate200>

/**
 * @description Local de estoque não encontrado
 */
export const localEstoqueControllerUpdate404Schema = z.unknown() as unknown as ToZod<LocalEstoqueControllerUpdate404>

/**
 * @description Nome já está em uso para este parceiro
 */
export const localEstoqueControllerUpdate409Schema = z.unknown() as unknown as ToZod<LocalEstoqueControllerUpdate409>

/**
 * @description Dados para atualização do local de estoque
 */
export const localEstoqueControllerUpdateMutationRequestSchema = z.lazy(() => updateLocalEstoqueDtoSchema) as unknown as ToZod<LocalEstoqueControllerUpdateMutationRequest>

export const localEstoqueControllerUpdateMutationResponseSchema = z.lazy(() => localEstoqueControllerUpdate200Schema) as unknown as ToZod<LocalEstoqueControllerUpdateMutationResponse>