/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MonthItemDto } from "../types/MonthItemDto.ts";
import { z } from "zod/v4";

export const monthItemDtoSchema = z.object({
    "ano": z.coerce.string().describe("Ano"),
"mes": z.coerce.number().describe("Mês (1-12)"),
"total": z.coerce.number().describe("Total de despesas no mês")
    }) as unknown as z.ZodType<MonthItemDto>