/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MovimentoEstoqueControllerAjusteEstoque201, MovimentoEstoqueControllerAjusteEstoque400, MovimentoEstoqueControllerAjusteEstoque404, MovimentoEstoqueControllerAjusteEstoqueMutationRequest, MovimentoEstoqueControllerAjusteEstoqueMutationResponse } from "../types/MovimentoEstoqueControllerAjusteEstoque.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { ajusteEstoqueDtoSchema } from "./ajusteEstoqueDtoSchema.ts";
import { movimentoEstoqueResponseDtoSchema } from "./movimentoEstoqueResponseDtoSchema.ts";
import { z } from "zod";

/**
 * @description Ajuste realizado com sucesso
 */
export const movimentoEstoqueControllerAjusteEstoque201Schema = z.lazy(() => movimentoEstoqueResponseDtoSchema) as unknown as ToZod<MovimentoEstoqueControllerAjusteEstoque201>

/**
 * @description Dados inválidos ou estoque insuficiente para ajuste negativo
 */
export const movimentoEstoqueControllerAjusteEstoque400Schema = z.unknown() as unknown as ToZod<MovimentoEstoqueControllerAjusteEstoque400>

/**
 * @description SKU ou local não encontrado
 */
export const movimentoEstoqueControllerAjusteEstoque404Schema = z.unknown() as unknown as ToZod<MovimentoEstoqueControllerAjusteEstoque404>

export const movimentoEstoqueControllerAjusteEstoqueMutationRequestSchema = z.lazy(() => ajusteEstoqueDtoSchema) as unknown as ToZod<MovimentoEstoqueControllerAjusteEstoqueMutationRequest>

export const movimentoEstoqueControllerAjusteEstoqueMutationResponseSchema = z.lazy(() => movimentoEstoqueControllerAjusteEstoque201Schema) as unknown as ToZod<MovimentoEstoqueControllerAjusteEstoqueMutationResponse>