/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PagamentoControllerRemovePathParams, PagamentoControllerRemoveHeaderParams, PagamentoControllerRemove204, PagamentoControllerRemove404, PagamentoControllerRemoveMutationResponse } from "../types/PagamentoControllerRemove.ts";
import { z } from "zod/v4";

export const pagamentoControllerRemovePathParamsSchema = z.object({
    "id": z.coerce.number().describe("ID do pagamento")
    }) as unknown as z.ZodType<PagamentoControllerRemovePathParams>

export const pagamentoControllerRemoveHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<PagamentoControllerRemoveHeaderParams>

/**
 * @description Pagamento removido com sucesso
 */
export const pagamentoControllerRemove204Schema = z.unknown() as unknown as z.ZodType<PagamentoControllerRemove204>

/**
 * @description Pagamento não encontrado
 */
export const pagamentoControllerRemove404Schema = z.unknown() as unknown as z.ZodType<PagamentoControllerRemove404>

export const pagamentoControllerRemoveMutationResponseSchema = pagamentoControllerRemove204Schema as unknown as z.ZodType<PagamentoControllerRemoveMutationResponse>