/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedMovimentoEstoqueResponseDto } from "../types/PaginatedMovimentoEstoqueResponseDto.ts";
import { movimentoEstoqueResponseDtoSchema } from "./movimentoEstoqueResponseDtoSchema.ts";
import { z } from "zod/v4";

export const paginatedMovimentoEstoqueResponseDtoSchema = z.object({
    get "data"(){
                return z.array(movimentoEstoqueResponseDtoSchema).describe("Lista de movimentos de estoque")
              },
"total": z.coerce.number().describe("Total de registros"),
"page": z.coerce.number().describe("Página atual"),
"limit": z.coerce.number().describe("Limite de registros por página"),
"totalPages": z.coerce.number().describe("Total de páginas")
    }) as unknown as z.ZodType<PaginatedMovimentoEstoqueResponseDto>