/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ParcelasControllerRemovePathParams, ParcelasControllerRemove204, ParcelasControllerRemoveMutationResponse } from "../types/ParcelasControllerRemove.ts";
import { z } from "zod/v4";

export const parcelasControllerRemovePathParamsSchema = z.object({
    "id": z.coerce.number()
    }) as unknown as z.ZodType<ParcelasControllerRemovePathParams>

/**
 * @description Parcela removida
 */
export const parcelasControllerRemove204Schema = z.unknown() as unknown as z.ZodType<ParcelasControllerRemove204>

export const parcelasControllerRemoveMutationResponseSchema = parcelasControllerRemove204Schema as unknown as z.ZodType<ParcelasControllerRemoveMutationResponse>