/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ParcelamentoControllerRemovePathParams, ParcelamentoControllerRemove204, ParcelamentoControllerRemoveMutationResponse } from "../types/ParcelamentoControllerRemove.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const parcelamentoControllerRemovePathParamsSchema = z.object({
      "id": z.coerce.number()
      }) as unknown as ToZod<ParcelamentoControllerRemovePathParams>

/**
 * @description Parcelamento removido
 */
export const parcelamentoControllerRemove204Schema = z.unknown() as unknown as ToZod<ParcelamentoControllerRemove204>

export const parcelamentoControllerRemoveMutationResponseSchema = z.lazy(() => parcelamentoControllerRemove204Schema) as unknown as ToZod<ParcelamentoControllerRemoveMutationResponse>