/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ParcelaDto } from "../types/ParcelaDto.ts";
import { z } from "zod/v4";

export const parcelaDtoSchema = z.object({
    "id": z.coerce.number().describe("ID da parcela"),
"parcelamentoId": z.coerce.number().describe("ID do parcelamento"),
"numero": z.coerce.number().describe("Número da parcela"),
"valor": z.coerce.number().describe("Valor da parcela"),
"vencimento": z.nullable(z.string().datetime().describe("Data de vencimento (null para parcelamento flexível)")),
"recebidoEm": z.nullable(z.string().datetime().describe("Data em que foi recebido")),
"status": z.enum(["PENDENTE", "PAGO", "PAGO_ATRASADO"]).describe("Status da parcela (PENDENTE, PAGO, PAGO_ATRASADO)")
    }) as unknown as z.ZodType<ParcelaDto>