/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ParceirosControllerActivateParceiroPathParams, ParceirosControllerActivateParceiro200, ParceirosControllerActivateParceiro404, ParceirosControllerActivateParceiroMutationResponse } from "../types/ParceirosControllerActivateParceiro.ts";
import { parceiroSchema } from "./parceiroSchema.ts";
import { z } from "zod/v4";

export const parceirosControllerActivateParceiroPathParamsSchema = z.object({
    "publicId": z.string().describe("ID público do parceiro")
    }) as unknown as z.ZodType<ParceirosControllerActivateParceiroPathParams>

/**
 * @description Parceiro ativado com sucesso
 */
export const parceirosControllerActivateParceiro200Schema = parceiroSchema as unknown as z.ZodType<ParceirosControllerActivateParceiro200>

/**
 * @description Parceiro não encontrado
 */
export const parceirosControllerActivateParceiro404Schema = z.unknown() as unknown as z.ZodType<ParceirosControllerActivateParceiro404>

export const parceirosControllerActivateParceiroMutationResponseSchema = parceirosControllerActivateParceiro200Schema as unknown as z.ZodType<ParceirosControllerActivateParceiroMutationResponse>