/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ParceirosControllerFindActiveParceiros200, ParceirosControllerFindActiveParceirosQueryResponse } from "../types/ParceirosControllerFindActiveParceiros.ts";
import { parceiroSchema } from "./parceiroSchema.ts";
import { z } from "zod/v4";

/**
 * @description Lista de parceiros ativos
 */
export const parceirosControllerFindActiveParceiros200Schema = z.array(parceiroSchema) as unknown as z.ZodType<ParceirosControllerFindActiveParceiros200>

export const parceirosControllerFindActiveParceirosQueryResponseSchema = parceirosControllerFindActiveParceiros200Schema as unknown as z.ZodType<ParceirosControllerFindActiveParceirosQueryResponse>