/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ParcelasControllerCreate201, ParcelasControllerCreateMutationRequest, ParcelasControllerCreateMutationResponse } from "../types/ParcelasControllerCreate.ts";
import { createParcelaDtoSchema } from "./createParcelaDtoSchema.ts";
import { parcelaSchema } from "./parcelaSchema.ts";
import { z } from "zod/v4";

/**
 * @description Parcela criada
 */
export const parcelasControllerCreate201Schema = parcelaSchema as unknown as z.ZodType<ParcelasControllerCreate201>

export const parcelasControllerCreateMutationRequestSchema = createParcelaDtoSchema as unknown as z.ZodType<ParcelasControllerCreateMutationRequest>

export const parcelasControllerCreateMutationResponseSchema = parcelasControllerCreate201Schema as unknown as z.ZodType<ParcelasControllerCreateMutationResponse>