/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PasswordResetControllerValidateTokenQueryParams,
  PasswordResetControllerValidateToken200,
  PasswordResetControllerValidateTokenQueryResponse,
} from '../types/PasswordResetControllerValidateToken.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'

export const passwordResetControllerValidateTokenQueryParamsSchema = z.object({
  token: z.string().describe('Token de recuperação de senha'),
}) as unknown as ToZod<PasswordResetControllerValidateTokenQueryParams>

/**
 * @description Status de validação do token
 */
export const passwordResetControllerValidateToken200Schema = z.object({
  valid: z.boolean().optional(),
  message: z.coerce.string().optional(),
}) as unknown as ToZod<PasswordResetControllerValidateToken200>

export const passwordResetControllerValidateTokenQueryResponseSchema = z.lazy(
  () => passwordResetControllerValidateToken200Schema,
) as unknown as ToZod<PasswordResetControllerValidateTokenQueryResponse>