/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PasswordResetControllerResetPassword200, PasswordResetControllerResetPassword400, PasswordResetControllerResetPasswordMutationRequest, PasswordResetControllerResetPasswordMutationResponse } from "../types/PasswordResetControllerResetPassword.ts";
import { passwordResetMessageResponseDtoSchema } from "./passwordResetMessageResponseDtoSchema.ts";
import { resetPasswordDtoSchema } from "./resetPasswordDtoSchema.ts";
import { z } from "zod/v4";

/**
 * @description Senha alterada com sucesso
 */
export const passwordResetControllerResetPassword200Schema = passwordResetMessageResponseDtoSchema as unknown as z.ZodType<PasswordResetControllerResetPassword200>

/**
 * @description Token inválido ou expirado
 */
export const passwordResetControllerResetPassword400Schema = z.unknown() as unknown as z.ZodType<PasswordResetControllerResetPassword400>

export const passwordResetControllerResetPasswordMutationRequestSchema = resetPasswordDtoSchema as unknown as z.ZodType<PasswordResetControllerResetPasswordMutationRequest>

export const passwordResetControllerResetPasswordMutationResponseSchema = passwordResetControllerResetPassword200Schema as unknown as z.ZodType<PasswordResetControllerResetPasswordMutationResponse>