/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PerfilSimpleDto } from "../types/PerfilSimpleDto.ts";
import { z } from "zod/v4";

export const perfilSimpleDtoSchema = z.object({
    "id": z.coerce.number(),
"nome": z.coerce.string()
    }) as unknown as z.ZodType<PerfilSimpleDto>