/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProdutoControllerFindByFornecedorPathParams, ProdutoControllerFindByFornecedorHeaderParams, ProdutoControllerFindByFornecedor200, ProdutoControllerFindByFornecedor404, ProdutoControllerFindByFornecedorQueryResponse } from "../types/ProdutoControllerFindByFornecedor.ts";
import { produtoSchema } from "./produtoSchema.ts";
import { z } from "zod/v4";

export const produtoControllerFindByFornecedorPathParamsSchema = z.object({
    "fornecedorPublicId": z.string().describe("ID público do fornecedor")
    }) as unknown as z.ZodType<ProdutoControllerFindByFornecedorPathParams>

export const produtoControllerFindByFornecedorHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<ProdutoControllerFindByFornecedorHeaderParams>

/**
 * @description Lista de produtos do fornecedor
 */
export const produtoControllerFindByFornecedor200Schema = z.array(produtoSchema) as unknown as z.ZodType<ProdutoControllerFindByFornecedor200>

/**
 * @description Fornecedor não encontrado
 */
export const produtoControllerFindByFornecedor404Schema = z.unknown() as unknown as z.ZodType<ProdutoControllerFindByFornecedor404>

export const produtoControllerFindByFornecedorQueryResponseSchema = produtoControllerFindByFornecedor200Schema as unknown as z.ZodType<ProdutoControllerFindByFornecedorQueryResponse>