/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProdutoControllerFindOnePathParams, ProdutoControllerFindOneHeaderParams, ProdutoControllerFindOne200, ProdutoControllerFindOne404, ProdutoControllerFindOneQueryResponse } from "../types/ProdutoControllerFindOne.ts";
import { produtoSchema } from "./produtoSchema.ts";
import { z } from "zod/v4";

export const produtoControllerFindOnePathParamsSchema = z.object({
    "publicId": z.string().describe("ID público do produto")
    }) as unknown as z.ZodType<ProdutoControllerFindOnePathParams>

export const produtoControllerFindOneHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<ProdutoControllerFindOneHeaderParams>

/**
 * @description Produto encontrado
 */
export const produtoControllerFindOne200Schema = produtoSchema as unknown as z.ZodType<ProdutoControllerFindOne200>

/**
 * @description Produto não encontrado
 */
export const produtoControllerFindOne404Schema = z.unknown() as unknown as z.ZodType<ProdutoControllerFindOne404>

export const produtoControllerFindOneQueryResponseSchema = produtoControllerFindOne200Schema as unknown as z.ZodType<ProdutoControllerFindOneQueryResponse>