/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProdutoHistoricoPrecoControllerGetLatestPricePathParams, ProdutoHistoricoPrecoControllerGetLatestPriceHeaderParams, ProdutoHistoricoPrecoControllerGetLatestPrice200, ProdutoHistoricoPrecoControllerGetLatestPrice204, ProdutoHistoricoPrecoControllerGetLatestPrice404, ProdutoHistoricoPrecoControllerGetLatestPriceQueryResponse } from "../types/ProdutoHistoricoPrecoControllerGetLatestPrice.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { produtoHistoricoPrecoResponseDtoSchema } from "./produtoHistoricoPrecoResponseDtoSchema.ts";
import { z } from "zod";

export const produtoHistoricoPrecoControllerGetLatestPricePathParamsSchema = z.object({
      "produtoId": z.coerce.number().int().describe("ID numérico do produto")
      }) as unknown as ToZod<ProdutoHistoricoPrecoControllerGetLatestPricePathParams>

export const produtoHistoricoPrecoControllerGetLatestPriceHeaderParamsSchema = z.object({
      "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
      }) as unknown as ToZod<ProdutoHistoricoPrecoControllerGetLatestPriceHeaderParams>

/**
 * @description Último preço registrado do produto
 */
export const produtoHistoricoPrecoControllerGetLatestPrice200Schema = z.lazy(() => produtoHistoricoPrecoResponseDtoSchema) as unknown as ToZod<ProdutoHistoricoPrecoControllerGetLatestPrice200>

/**
 * @description Nenhum histórico de preço encontrado para o produto
 */
export const produtoHistoricoPrecoControllerGetLatestPrice204Schema = z.unknown() as unknown as ToZod<ProdutoHistoricoPrecoControllerGetLatestPrice204>

/**
 * @description Produto não encontrado
 */
export const produtoHistoricoPrecoControllerGetLatestPrice404Schema = z.unknown() as unknown as ToZod<ProdutoHistoricoPrecoControllerGetLatestPrice404>

export const produtoHistoricoPrecoControllerGetLatestPriceQueryResponseSchema = z.union([z.lazy(() => produtoHistoricoPrecoControllerGetLatestPrice200Schema), z.lazy(() => produtoHistoricoPrecoControllerGetLatestPrice204Schema)]) as unknown as ToZod<ProdutoHistoricoPrecoControllerGetLatestPriceQueryResponse>