/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RegraLancamentoControllerUpdatePathParams, RegraLancamentoControllerUpdateHeaderParams, RegraLancamentoControllerUpdate200, RegraLancamentoControllerUpdate401, RegraLancamentoControllerUpdate404, RegraLancamentoControllerUpdate409, RegraLancamentoControllerUpdateMutationRequest, RegraLancamentoControllerUpdateMutationResponse } from "../types/RegraLancamentoControllerUpdate.ts";
import { regraLancamentoAutomaticoSchema } from "./regraLancamentoAutomaticoSchema.ts";
import { updateRegraLancamentoDtoSchema } from "./updateRegraLancamentoDtoSchema.ts";
import { z } from "zod/v4";

export const regraLancamentoControllerUpdatePathParamsSchema = z.object({
    "id": z.coerce.number().describe("ID da regra de lançamento")
    }) as unknown as z.ZodType<RegraLancamentoControllerUpdatePathParams>

export const regraLancamentoControllerUpdateHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<RegraLancamentoControllerUpdateHeaderParams>

/**
 * @description Regra de lançamento atualizada com sucesso
 */
export const regraLancamentoControllerUpdate200Schema = regraLancamentoAutomaticoSchema as unknown as z.ZodType<RegraLancamentoControllerUpdate200>

/**
 * @description Não autorizado
 */
export const regraLancamentoControllerUpdate401Schema = z.unknown() as unknown as z.ZodType<RegraLancamentoControllerUpdate401>

/**
 * @description Regra de lançamento não encontrada
 */
export const regraLancamentoControllerUpdate404Schema = z.unknown() as unknown as z.ZodType<RegraLancamentoControllerUpdate404>

/**
 * @description Já existe uma regra com este nome para este parceiro
 */
export const regraLancamentoControllerUpdate409Schema = z.unknown() as unknown as z.ZodType<RegraLancamentoControllerUpdate409>

export const regraLancamentoControllerUpdateMutationRequestSchema = updateRegraLancamentoDtoSchema as unknown as z.ZodType<RegraLancamentoControllerUpdateMutationRequest>

export const regraLancamentoControllerUpdateMutationResponseSchema = regraLancamentoControllerUpdate200Schema as unknown as z.ZodType<RegraLancamentoControllerUpdateMutationResponse>