/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RegraLancamentoAutomatico } from "../types/RegraLancamentoAutomatico.ts";
import { iSchema } from "./iSchema.ts";
import { z } from "zod/v4";

export const regraLancamentoAutomaticoSchema = z.object({
    "id": z.coerce.number().describe("ID interno da regra"),
"publicId": z.coerce.string().describe("ID público (UUID) da regra"),
"contaDreId": z.coerce.number().describe("ID da conta DRE associada"),
"parceiroId": z.coerce.number().describe("ID do parceiro"),
"impostoId": z.optional(z.coerce.number().describe("ID do imposto (para deduções)")),
"nome": z.coerce.string().describe("Nome da regra"),
"tipoGatilho": z.coerce.string().describe("Tipo de gatilho (VENDA_CONFIRMADA, VENDA_COM_FATURA)"),
"tipoVenda": z.optional(z.coerce.string().describe("Tipo de venda para filtrar (DIRETA, CONDICIONAL, BRINDE, PERMUTA)")),
"campoOrigem": z.optional(z.coerce.string().describe("Campo origem para o cálculo (valorTotal, valorFrete, valorComissao)")),
get "percentual"(){
                return iSchema.describe("Percentual a aplicar (sobrescreve imposto se informado)").optional()
              },
"ativo": z.boolean().default(true).describe("Status ativo da regra"),
"createdAt": z.string().datetime().describe("Data de criação da regra")
    }) as unknown as z.ZodType<RegraLancamentoAutomatico>