/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RegraLancamentoControllerRemovePathParams, RegraLancamentoControllerRemoveHeaderParams, RegraLancamentoControllerRemove200, RegraLancamentoControllerRemove401, RegraLancamentoControllerRemove404, RegraLancamentoControllerRemoveMutationResponse } from "../types/RegraLancamentoControllerRemove.ts";
import { z } from "zod/v4";

export const regraLancamentoControllerRemovePathParamsSchema = z.object({
    "id": z.coerce.number().describe("ID da regra de lançamento")
    }) as unknown as z.ZodType<RegraLancamentoControllerRemovePathParams>

export const regraLancamentoControllerRemoveHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<RegraLancamentoControllerRemoveHeaderParams>

/**
 * @description Regra de lançamento removida com sucesso
 */
export const regraLancamentoControllerRemove200Schema = z.unknown() as unknown as z.ZodType<RegraLancamentoControllerRemove200>

/**
 * @description Não autorizado
 */
export const regraLancamentoControllerRemove401Schema = z.unknown() as unknown as z.ZodType<RegraLancamentoControllerRemove401>

/**
 * @description Regra de lançamento não encontrada
 */
export const regraLancamentoControllerRemove404Schema = z.unknown() as unknown as z.ZodType<RegraLancamentoControllerRemove404>

export const regraLancamentoControllerRemoveMutationResponseSchema = regraLancamentoControllerRemove200Schema as unknown as z.ZodType<RegraLancamentoControllerRemoveMutationResponse>