/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RegraLancamentoControllerFindAllHeaderParams, RegraLancamentoControllerFindAll200, RegraLancamentoControllerFindAll401, RegraLancamentoControllerFindAllQueryResponse } from "../types/RegraLancamentoControllerFindAll.ts";
import { regraLancamentoAutomaticoSchema } from "./regraLancamentoAutomaticoSchema.ts";
import { z } from "zod/v4";

export const regraLancamentoControllerFindAllHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<RegraLancamentoControllerFindAllHeaderParams>

/**
 * @description Lista de regras de lançamento retornada com sucesso
 */
export const regraLancamentoControllerFindAll200Schema = z.array(regraLancamentoAutomaticoSchema) as unknown as z.ZodType<RegraLancamentoControllerFindAll200>

/**
 * @description Não autorizado
 */
export const regraLancamentoControllerFindAll401Schema = z.unknown() as unknown as z.ZodType<RegraLancamentoControllerFindAll401>

export const regraLancamentoControllerFindAllQueryResponseSchema = regraLancamentoControllerFindAll200Schema as unknown as z.ZodType<RegraLancamentoControllerFindAllQueryResponse>