/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RollupClassificacaoControllerGetClassesAnoQueryParams, RollupClassificacaoControllerGetClassesAno200, RollupClassificacaoControllerGetClassesAnoQueryResponse } from "../types/RollupClassificacaoControllerGetClassesAno.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const rollupClassificacaoControllerGetClassesAnoQueryParamsSchema = z.object({
      "parceiroId": z.string(),
  "yyyy": z.string()
      }) as unknown as ToZod<RollupClassificacaoControllerGetClassesAnoQueryParams>

export const rollupClassificacaoControllerGetClassesAno200Schema = z.unknown() as unknown as ToZod<RollupClassificacaoControllerGetClassesAno200>

export const rollupClassificacaoControllerGetClassesAnoQueryResponseSchema = z.lazy(() => rollupClassificacaoControllerGetClassesAno200Schema) as unknown as ToZod<RollupClassificacaoControllerGetClassesAnoQueryResponse>