/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateParcelamentoDto } from "../types/UpdateParcelamentoDto.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const updateParcelamentoDtoSchema = z.object({
      "idPagamento": z.coerce.number().describe("ID do pagamento associado").optional(),
  "clienteId": z.coerce.number().describe("ID do cliente associado").optional(),
  "valorTotal": z.coerce.number().describe("Valor total parcelado").optional(),
  "valorPago": z.coerce.number().default(0).describe("Valor já pago"),
  "idFormaPag": z.coerce.number().describe("ID da forma de pagamento").optional(),
  "situacao": z.coerce.number().default(1).describe("Situação (1 - Aberto, 2 - Concluído)")
      }) as unknown as ToZod<UpdateParcelamentoDto>