/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateCurrencyDto } from '../types/UpdateCurrencyDto.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'

export const updateCurrencyDtoSchema = z.object({
  nome: z.coerce.string().describe('Nome da moeda').optional(),
  prefixo: z.coerce.string().describe('Prefixo da moeda').optional(),
  isoCode: z.coerce.string().describe('Código ISO da moeda').optional(),
  precision: z.coerce.number().default(2).describe('Precisão decimal da moeda'),
  locale: z.coerce.string().default('pt-BR').describe('Locale para formatação'),
  defaultRate: z.coerce.number().default(0).describe('Taxa de câmbio padrão'),
  ativo: z.boolean().default(true).describe('Status ativo da moeda'),
}) as unknown as ToZod<UpdateCurrencyDto>
