/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateContasPagarParcelasDto } from '../types/UpdateContasPagarParcelasDto.ts'
import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'

export const updateContasPagarParcelasDtoSchema = z.object({
  dataPagamento: z.coerce.string().describe('Data do pagamento da parcela').optional(),
  dataVencimento: z.coerce.string().describe('Data de vencimento da parcela').optional(),
  valor: z.coerce.number().describe('Valor da parcela').optional(),
  pago: z.boolean().describe('Se a parcela foi paga').optional(),
  contasPagarId: z.coerce.number().describe('ID da conta a pagar relacionada').optional(),
}) as unknown as ToZod<UpdateContasPagarParcelasDto>