/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateVendaDto } from "../types/UpdateVendaDto.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const updateVendaDtoSchema = z.object({
      "clienteId": z.coerce.number().describe("ID do cliente").optional(),
  "localSaidaId": z.coerce.number().describe("ID do local de saída").optional(),
  "tipo": z.enum(["DIRETA", "CONDICIONAL", "BRINDE"]).default("DIRETA").describe("Tipo da venda"),
  "dataEntrega": z.coerce.string().describe("Data de entrega").optional(),
  "valorFrete": z.coerce.number().describe("Valor do frete").optional(),
  "desconto": z.coerce.number().describe("Desconto total da venda").optional(),
  "ruccnpj": z.coerce.string().describe("RUC/CNPJ da fatura da venda").optional(),
  "numeroFatura": z.coerce.string().describe("Número da fatura").optional(),
  "observacao": z.coerce.string().describe("Observação da venda").optional(),
  "valorComissao": z.coerce.number().describe("Valor da comissão").optional()
      }) as unknown as ToZod<UpdateVendaDto>