/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateVendaItemDto } from "../types/UpdateVendaItemDto.ts";
import type { ToZod } from "@kubb/plugin-zod/utils";
import { z } from "zod";

export const updateVendaItemDtoSchema = z.object({
      "vendaId": z.coerce.number().describe("ID da venda").optional(),
  "skuId": z.coerce.number().describe("ID do SKU").optional(),
  "tipo": z.enum(["NORMAL", "BRINDE"]).describe("Tipo do item").optional(),
  "qtdReservada": z.coerce.number().describe("Quantidade reservada").optional(),
  "qtdAceita": z.coerce.number().describe("Quantidade aceita (cliente ficou)").optional(),
  "qtdDevolvida": z.coerce.number().describe("Quantidade devolvida").optional(),
  "desconto": z.coerce.number().describe("Desconto por item").optional(),
  "precoUnit": z.coerce.number().describe("Preço unitário").optional()
      }) as unknown as ToZod<UpdateVendaItemDto>