/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateVendaDto } from "../types/UpdateVendaDto.ts";
import { z } from "zod/v4";

export const updateVendaDtoSchema = z.object({
    "clienteId": z.optional(z.coerce.number().describe("ID do cliente")),
"localSaidaId": z.optional(z.coerce.number().describe("ID do local de saída")),
"tipo": z.optional(z.enum(["DIRETA", "CONDICIONAL", "BRINDE", "PERMUTA"]).default("DIRETA").describe("Tipo da venda")),
"dataEntrega": z.optional(z.coerce.string().describe("Data de entrega")),
"valorFrete": z.optional(z.coerce.number().describe("Valor do frete")),
"desconto": z.optional(z.coerce.number().describe("Desconto total da venda")),
"ruccnpj": z.optional(z.coerce.string().describe("RUC/CNPJ da fatura da venda")),
"nomeFatura": z.optional(z.coerce.string().describe("Nome para a fatura da venda")),
"numeroFatura": z.optional(z.coerce.string().describe("Número da fatura")),
"observacao": z.optional(z.coerce.string().describe("Observação da venda")),
"valorComissao": z.optional(z.coerce.number().describe("Valor da comissão"))
    }) as unknown as z.ZodType<UpdateVendaDto>