/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserDto } from "../types/UserDto.ts";
import { perfilDtoSchema } from "./perfilDtoSchema.ts";
import { z } from "zod/v4";

export const userDtoSchema = z.object({
    "id": z.coerce.number(),
"publicId": z.coerce.string(),
"nome": z.coerce.string(),
"email": z.coerce.string(),
"telefone": z.optional(z.coerce.string()),
"ativo": z.boolean(),
get "perfil"(){
                return perfilDtoSchema
              }
    }) as unknown as z.ZodType<UserDto>