/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsuarioParceiroControllerFindByUsuarioPathParams, UsuarioParceiroControllerFindByUsuario200, UsuarioParceiroControllerFindByUsuarioQueryResponse } from "../types/UsuarioParceiroControllerFindByUsuario.ts";
import { usuarioParceiroSchema } from "./usuarioParceiroSchema.ts";
import { z } from "zod/v4";

export const usuarioParceiroControllerFindByUsuarioPathParamsSchema = z.object({
    "usuarioId": z.coerce.number().describe("ID do usuário")
    }) as unknown as z.ZodType<UsuarioParceiroControllerFindByUsuarioPathParams>

/**
 * @description Lista de relações do usuário
 */
export const usuarioParceiroControllerFindByUsuario200Schema = z.array(usuarioParceiroSchema) as unknown as z.ZodType<UsuarioParceiroControllerFindByUsuario200>

export const usuarioParceiroControllerFindByUsuarioQueryResponseSchema = usuarioParceiroControllerFindByUsuario200Schema as unknown as z.ZodType<UsuarioParceiroControllerFindByUsuarioQueryResponse>