/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsuariosControllerActivateUserPathParams, UsuariosControllerActivateUser200, UsuariosControllerActivateUser404, UsuariosControllerActivateUserMutationResponse } from "../types/UsuariosControllerActivateUser.ts";
import { usuarioSchema } from "./usuarioSchema.ts";
import { z } from "zod/v4";

export const usuariosControllerActivateUserPathParamsSchema = z.object({
    "publicId": z.string().describe("ID público do usuário (UUID v7)")
    }) as unknown as z.ZodType<UsuariosControllerActivateUserPathParams>

/**
 * @description Usuário ativado com sucesso
 */
export const usuariosControllerActivateUser200Schema = usuarioSchema as unknown as z.ZodType<UsuariosControllerActivateUser200>

/**
 * @description Usuário não encontrado
 */
export const usuariosControllerActivateUser404Schema = z.unknown() as unknown as z.ZodType<UsuariosControllerActivateUser404>

export const usuariosControllerActivateUserMutationResponseSchema = usuariosControllerActivateUser200Schema as unknown as z.ZodType<UsuariosControllerActivateUserMutationResponse>