/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsuariosControllerFindOnePathParams, UsuariosControllerFindOne200, UsuariosControllerFindOne404, UsuariosControllerFindOneQueryResponse } from "../types/UsuariosControllerFindOne.ts";
import { usuarioSchema } from "./usuarioSchema.ts";
import { z } from "zod/v4";

export const usuariosControllerFindOnePathParamsSchema = z.object({
    "publicId": z.string().describe("ID público do usuário (UUID v7)")
    }) as unknown as z.ZodType<UsuariosControllerFindOnePathParams>

/**
 * @description Usuário encontrado com sucesso
 */
export const usuariosControllerFindOne200Schema = usuarioSchema as unknown as z.ZodType<UsuariosControllerFindOne200>

/**
 * @description Usuário não encontrado
 */
export const usuariosControllerFindOne404Schema = z.unknown() as unknown as z.ZodType<UsuariosControllerFindOne404>

export const usuariosControllerFindOneQueryResponseSchema = usuariosControllerFindOne200Schema as unknown as z.ZodType<UsuariosControllerFindOneQueryResponse>