/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsuariosControllerFindAll200, UsuariosControllerFindAllQueryResponse } from "../types/UsuariosControllerFindAll.ts";
import { usuarioSchema } from "./usuarioSchema.ts";
import { z } from "zod/v4";

/**
 * @description Lista de usuários retornada com sucesso
 */
export const usuariosControllerFindAll200Schema = z.array(usuarioSchema) as unknown as z.ZodType<UsuariosControllerFindAll200>

export const usuariosControllerFindAllQueryResponseSchema = usuariosControllerFindAll200Schema as unknown as z.ZodType<UsuariosControllerFindAllQueryResponse>