/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VendaItemControllerRemovePathParams, VendaItemControllerRemoveQueryParams, VendaItemControllerRemoveHeaderParams, VendaItemControllerRemove204, VendaItemControllerRemove400, VendaItemControllerRemove404, VendaItemControllerRemoveMutationResponse } from "../types/VendaItemControllerRemove.ts";
import { z } from "zod/v4";

export const vendaItemControllerRemovePathParamsSchema = z.object({
    "id": z.string().describe("ID do item")
    }) as unknown as z.ZodType<VendaItemControllerRemovePathParams>

export const vendaItemControllerRemoveQueryParamsSchema = z.object({
    "vendaId": z.string()
    }) as unknown as z.ZodType<VendaItemControllerRemoveQueryParams>

export const vendaItemControllerRemoveHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<VendaItemControllerRemoveHeaderParams>

/**
 * @description Item removido com sucesso
 */
export const vendaItemControllerRemove204Schema = z.unknown() as unknown as z.ZodType<VendaItemControllerRemove204>

/**
 * @description Exclusão permitida apenas com status PEDIDO
 */
export const vendaItemControllerRemove400Schema = z.unknown() as unknown as z.ZodType<VendaItemControllerRemove400>

/**
 * @description Item não encontrado
 */
export const vendaItemControllerRemove404Schema = z.unknown() as unknown as z.ZodType<VendaItemControllerRemove404>

export const vendaItemControllerRemoveMutationResponseSchema = vendaItemControllerRemove204Schema as unknown as z.ZodType<VendaItemControllerRemoveMutationResponse>