/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VendaItemControllerFindAllQueryParams, VendaItemControllerFindAllHeaderParams, VendaItemControllerFindAll200, VendaItemControllerFindAllQueryResponse } from "../types/VendaItemControllerFindAll.ts";
import { vendaItemEntitySchema } from "./vendaItemEntitySchema.ts";
import { z } from "zod/v4";

export const vendaItemControllerFindAllQueryParamsSchema = z.object({
    "vendaId": z.string()
    }) as unknown as z.ZodType<VendaItemControllerFindAllQueryParams>

export const vendaItemControllerFindAllHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<VendaItemControllerFindAllHeaderParams>

/**
 * @description Lista de itens
 */
export const vendaItemControllerFindAll200Schema = z.array(vendaItemEntitySchema) as unknown as z.ZodType<VendaItemControllerFindAll200>

export const vendaItemControllerFindAllQueryResponseSchema = vendaItemControllerFindAll200Schema as unknown as z.ZodType<VendaItemControllerFindAllQueryResponse>