/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Venda } from "../types/Venda.ts";
import { pagamentoEntitySchema } from "./pagamentoEntitySchema.ts";
import { vendaItemEntitySchema } from "./vendaItemEntitySchema.ts";
import { z } from "zod/v4";

export const vendaSchema = z.object({
    "id": z.coerce.number().describe("ID interno da venda"),
"publicId": z.coerce.string().describe("ID público da venda"),
"usuarioId": z.coerce.number().describe("ID do usuário que criou a venda"),
"parceiroId": z.coerce.number().describe("ID do parceiro"),
"localSaidaId": z.coerce.number().describe("ID do local de saída"),
"clienteId": z.coerce.number().describe("ID do cliente"),
"tipo": z.enum(["DIRETA", "CONDICIONAL", "BRINDE", "PERMUTA"]).describe("Tipo da venda"),
"status": z.enum(["PEDIDO", "ABERTA", "CONFIRMADA", "CONFIRMADA_PARCIAL", "CONFIRMADA_TOTAL", "CANCELADA"]).describe("Status da venda"),
"dataVenda": z.string().datetime().describe("Data da venda"),
"dataEntrega": z.optional(z.string().datetime().describe("Data de entrega")),
"valorFrete": z.optional(z.coerce.number().describe("Valor do frete")),
"desconto": z.optional(z.coerce.number().describe("Desconto total da venda")),
"valorTotal": z.optional(z.coerce.number().describe("Valor total da venda")),
"ruccnpj": z.optional(z.coerce.string().describe("RUC/CNPJ da fatura da venda")),
"nomeFatura": z.optional(z.coerce.string().describe("Nome para a fatura da venda")),
"numeroFatura": z.optional(z.coerce.string().describe("Número da fatura")),
"observacao": z.optional(z.coerce.string().describe("Observação da venda")),
"valorComissao": z.optional(z.coerce.number().describe("Valor da comissão")),
"clienteNome": z.optional(z.coerce.string().describe("Nome do cliente")),
"usuarioNome": z.optional(z.coerce.string().describe("Nome do usuário que criou a venda")),
get "VendaItem"(){
                return z.array(vendaItemEntitySchema).describe("Itens vendidos").optional()
              },
get "Pagamento"(){
                return z.array(pagamentoEntitySchema).describe("Pagamentos da venda").optional()
              }
    }) as unknown as z.ZodType<Venda>