/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VendaControllerProcessarDevolucaoPathParams, VendaControllerProcessarDevolucaoHeaderParams, VendaControllerProcessarDevolucao200, VendaControllerProcessarDevolucaoMutationRequest, VendaControllerProcessarDevolucaoMutationResponse } from "../types/VendaControllerProcessarDevolucao.ts";
import { processDevolucaoItemDtoSchema } from "./processDevolucaoItemDtoSchema.ts";
import { vendaSchema } from "./vendaSchema.ts";
import { z } from "zod/v4";

export const vendaControllerProcessarDevolucaoPathParamsSchema = z.object({
    "publicId": z.string().describe("ID público da venda")
    }) as unknown as z.ZodType<VendaControllerProcessarDevolucaoPathParams>

export const vendaControllerProcessarDevolucaoHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<VendaControllerProcessarDevolucaoHeaderParams>

/**
 * @description Devolução processada
 */
export const vendaControllerProcessarDevolucao200Schema = vendaSchema as unknown as z.ZodType<VendaControllerProcessarDevolucao200>

export const vendaControllerProcessarDevolucaoMutationRequestSchema = processDevolucaoItemDtoSchema as unknown as z.ZodType<VendaControllerProcessarDevolucaoMutationRequest>

export const vendaControllerProcessarDevolucaoMutationResponseSchema = vendaControllerProcessarDevolucao200Schema as unknown as z.ZodType<VendaControllerProcessarDevolucaoMutationResponse>