/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VendaControllerFinalizeDiretaPathParams, VendaControllerFinalizeDiretaHeaderParams, VendaControllerFinalizeDireta200, VendaControllerFinalizeDiretaMutationRequest, VendaControllerFinalizeDiretaMutationResponse } from "../types/VendaControllerFinalizeDireta.ts";
import { finalizeVendaDiretaDtoSchema } from "./finalizeVendaDiretaDtoSchema.ts";
import { vendaSchema } from "./vendaSchema.ts";
import { z } from "zod/v4";

export const vendaControllerFinalizeDiretaPathParamsSchema = z.object({
    "publicId": z.string().describe("ID público da venda")
    }) as unknown as z.ZodType<VendaControllerFinalizeDiretaPathParams>

export const vendaControllerFinalizeDiretaHeaderParamsSchema = z.object({
    "x-parceiro-id": z.coerce.number().int().describe("ID do parceiro logado")
    }) as unknown as z.ZodType<VendaControllerFinalizeDiretaHeaderParams>

/**
 * @description Venda finalizada
 */
export const vendaControllerFinalizeDireta200Schema = vendaSchema as unknown as z.ZodType<VendaControllerFinalizeDireta200>

export const vendaControllerFinalizeDiretaMutationRequestSchema = finalizeVendaDiretaDtoSchema as unknown as z.ZodType<VendaControllerFinalizeDiretaMutationRequest>

export const vendaControllerFinalizeDiretaMutationResponseSchema = vendaControllerFinalizeDireta200Schema as unknown as z.ZodType<VendaControllerFinalizeDiretaMutationResponse>