/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RefreshTokenDto } from "./RefreshTokenDto.ts";

/**
 * @description Token renovado com sucesso
*/
export type AuthControllerRefresh200 = {
    /**
     * @type string | undefined
    */
    accessToken?: string;
};

/**
 * @description Refresh token inválido
*/
export type AuthControllerRefresh401 = any;

export type AuthControllerRefreshMutationRequest = RefreshTokenDto;

export type AuthControllerRefreshMutationResponse = AuthControllerRefresh200;

export type AuthControllerRefreshMutation = {
    Response: AuthControllerRefresh200;
    Request: AuthControllerRefreshMutationRequest;
    Errors: AuthControllerRefresh401;
};