/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LogoutResponseDto } from "./LogoutResponseDto.ts";

/**
 * @description Logout realizado com sucesso
*/
export type AuthControllerLogout200 = LogoutResponseDto;

export type AuthControllerLogoutMutationResponse = AuthControllerLogout200;

export type AuthControllerLogoutMutation = {
    Response: AuthControllerLogout200;
    Errors: any;
};