/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Dados do usuário
 */
export type AuthControllerGetProfile200 = any

export type AuthControllerGetProfileQueryResponse = AuthControllerGetProfile200

export type AuthControllerGetProfileQuery = {
  Response: AuthControllerGetProfile200
  Errors: any
}
