/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserProfileDto } from "./UserProfileDto.ts";

/**
 * @description Dados do usuário
*/
export type AuthControllerGetProfile200 = UserProfileDto;

export type AuthControllerGetProfileQueryResponse = AuthControllerGetProfile200;

export type AuthControllerGetProfileQuery = {
    Response: AuthControllerGetProfile200;
    Errors: any;
};