/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CategoriaDespesasControllerRemovePathParams = {
  /**
   * @description ID da categoria de despesas
   * @type number
   */
  id: number
}

/**
 * @description Categoria de despesas removida com sucesso
 */
export type CategoriaDespesasControllerRemove200 = any

/**
 * @description Não autorizado
 */
export type CategoriaDespesasControllerRemove401 = any

/**
 * @description Categoria de despesas não encontrada
 */
export type CategoriaDespesasControllerRemove404 = any

export type CategoriaDespesasControllerRemoveMutationResponse = CategoriaDespesasControllerRemove200

export type CategoriaDespesasControllerRemoveMutation = {
  Response: CategoriaDespesasControllerRemove200
  PathParams: CategoriaDespesasControllerRemovePathParams
  Errors: CategoriaDespesasControllerRemove401 | CategoriaDespesasControllerRemove404
}