/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CategoriaDespesasControllerFindOnePathParams = {
    /**
     * @description ID da categoria de despesas
     * @type number
    */
    id: number;
};

/**
 * @description Categoria de despesas encontrada
*/
export type CategoriaDespesasControllerFindOne200 = {
    /**
     * @type number | undefined
    */
    idCategoria?: number | undefined;
    /**
     * @type string | undefined
    */
    descricao?: string | undefined;
    /**
     * @type boolean | undefined
    */
    ativo?: boolean | undefined;
    /**
     * @type string | undefined
    */
    createdAt?: string | undefined;
};

/**
 * @description Não autorizado
*/
export type CategoriaDespesasControllerFindOne401 = any;

/**
 * @description Categoria de despesas não encontrada
*/
export type CategoriaDespesasControllerFindOne404 = any;

export type CategoriaDespesasControllerFindOneQueryResponse = CategoriaDespesasControllerFindOne200;

export type CategoriaDespesasControllerFindOneQuery = {
    Response: CategoriaDespesasControllerFindOne200;
    PathParams: CategoriaDespesasControllerFindOnePathParams;
    Errors: CategoriaDespesasControllerFindOne401 | CategoriaDespesasControllerFindOne404;
};