/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CategoriaDespesas = {
  /**
   * @description ID interno da categoria de despesas
   * @type number
   */
  idCategoria: number
  /**
   * @description Descrição da categoria de despesas
   * @type string
   */
  descricao: string
  /**
   * @description Status ativo da categoria
   * @default true
   * @type boolean
   */
  ativo: boolean
  /**
   * @description Data de criação da categoria
   * @type string, date-time
   */
  createdAt: string
}