/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CategoriaProduto } from "./CategoriaProduto.ts";
import type { UpdateCategoriaProdutoDto } from "./UpdateCategoriaProdutoDto.ts";

export type CategoriaProdutoControllerUpdatePathParams = {
    /**
     * @description ID da categoria de produto
     * @type number
    */
    id: number;
};

/**
 * @description Categoria de produto atualizada com sucesso
*/
export type CategoriaProdutoControllerUpdate200 = CategoriaProduto;

/**
 * @description Dados de entrada inválidos
*/
export type CategoriaProdutoControllerUpdate400 = any;

/**
 * @description Categoria de produto não encontrada
*/
export type CategoriaProdutoControllerUpdate404 = any;

/**
 * @description Categoria com esta descrição já existe
*/
export type CategoriaProdutoControllerUpdate409 = any;

export type CategoriaProdutoControllerUpdateMutationRequest = UpdateCategoriaProdutoDto;

export type CategoriaProdutoControllerUpdateMutationResponse = CategoriaProdutoControllerUpdate200;

export type CategoriaProdutoControllerUpdateMutation = {
    Response: CategoriaProdutoControllerUpdate200;
    Request: CategoriaProdutoControllerUpdateMutationRequest;
    PathParams: CategoriaProdutoControllerUpdatePathParams;
    Errors: CategoriaProdutoControllerUpdate400 | CategoriaProdutoControllerUpdate404 | CategoriaProdutoControllerUpdate409;
};