/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CanalOrigem } from "./CanalOrigem.ts";
import type { Parceiro } from "./Parceiro.ts";

export const clienteLinguagemEnum = {
    "Espanol": "Espanol",
    "Portugues": "Portugues"
} as const;

export type ClienteLinguagemEnum = (typeof clienteLinguagemEnum)[keyof typeof clienteLinguagemEnum];

export type Cliente = {
    /**
     * @description ID único do cliente
     * @type number
    */
    id: number;
    /**
     * @description ID público do cliente
     * @type string
    */
    publicId: string;
    /**
     * @description Nome do cliente
     * @type string
    */
    nome: string;
    /**
     * @description Sobrenome do cliente
     * @type string | undefined
    */
    sobrenome?: string;
    /**
     * @description Email do cliente
     * @type string | undefined
    */
    email?: string;
    /**
     * @description Rede social do cliente
     * @type string | undefined
    */
    redeSocial?: string;
    /**
     * @description Celular do cliente
     * @type string | undefined
    */
    celular?: string;
    /**
     * @description RUC/CNPJ do cliente
     * @type string | undefined
    */
    ruccnpj?: string;
    /**
     * @description RUC/CNPJ secundario do cliente
     * @type string | undefined
    */
    ruccnpjSecundario?: string;
    /**
     * @description Nome da fatura do cliente (caso não seja o mesmo nome do cliente)
     * @type string | undefined
    */
    nomeFatura?: string;
    /**
     * @description Endereço do cliente
     * @type string | undefined
    */
    endereco?: string;
    /**
     * @description Cidade do cliente
     * @type string | undefined
    */
    cidade?: string;
    /**
     * @description CEP do cliente
     * @type string | undefined
    */
    cep?: string;
    /**
     * @description Observações sobre o cliente
     * @type string | undefined
    */
    observacoes?: string;
    /**
     * @description Linguagem preferida do cliente
     * @type string
    */
    linguagem: ClienteLinguagemEnum;
    /**
     * @description Status ativo do cliente
     * @type boolean
    */
    ativo: boolean;
    /**
     * @description ID do parceiro associado
     * @type number
    */
    parceiroId: number;
    /**
     * @description ID do canal de origem
     * @type number | undefined
    */
    canalOrigemId?: number;
    /**
     * @description Data de criação do cliente
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @description Data de atualização do cliente
     * @type string, date-time
    */
    updatedAt: string;
    /**
     * @description Data da última compra do cliente
     * @type string, date-time
    */
    ultimaCompra: string;
    /**
     * @description Quantidade de compras do cliente
     * @type number
    */
    qtdCompras: number;
    /**
     * @description Parceiro associado ao cliente
    */
    parceiro?: Parceiro;
    /**
     * @description Canal de origem do cliente
    */
    canalOrigem?: CanalOrigem;
};