/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Cliente } from './Cliente.ts'
import type { CreateClienteDto } from './CreateClienteDto.ts'

/**
 * @description Cliente criado com sucesso
 */
export type ClientesControllerCreate201 = Cliente

/**
 * @description Dados inválidos
 */
export type ClientesControllerCreate400 = any

/**
 * @description Email já está em uso
 */
export type ClientesControllerCreate409 = any

export type ClientesControllerCreateMutationRequest = CreateClienteDto

export type ClientesControllerCreateMutationResponse = ClientesControllerCreate201

export type ClientesControllerCreateMutation = {
  Response: ClientesControllerCreate201
  Request: ClientesControllerCreateMutationRequest
  Errors: ClientesControllerCreate400 | ClientesControllerCreate409
}