/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Cliente } from "./Cliente.ts";

export type ClientesControllerDeactivatePathParams = {
    /**
     * @description ID público do cliente
     * @type string
    */
    publicId: string;
};

/**
 * @description Cliente desativado com sucesso
*/
export type ClientesControllerDeactivate200 = Cliente;

/**
 * @description Cliente não encontrado
*/
export type ClientesControllerDeactivate404 = any;

export type ClientesControllerDeactivateMutationResponse = ClientesControllerDeactivate200;

export type ClientesControllerDeactivateMutation = {
    Response: ClientesControllerDeactivate200;
    PathParams: ClientesControllerDeactivatePathParams;
    Errors: ClientesControllerDeactivate404;
};