/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConferenciaEstoqueResponseDto } from "./ConferenciaEstoqueResponseDto.ts";
import type { UpdateConferenciaEstoqueDto } from "./UpdateConferenciaEstoqueDto.ts";

export type ConferenciaEstoqueControllerUpdatePathParams = {
    /**
     * @description ID público da conferência de estoque
     * @type string
    */
    publicId: string;
};

export type ConferenciaEstoqueControllerUpdateHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Conferência de estoque atualizada com sucesso
*/
export type ConferenciaEstoqueControllerUpdate200 = ConferenciaEstoqueResponseDto;

/**
 * @description Dados inválidos ou conferência finalizada
*/
export type ConferenciaEstoqueControllerUpdate400 = any;

/**
 * @description Conferência de estoque não encontrada
*/
export type ConferenciaEstoqueControllerUpdate404 = any;

export type ConferenciaEstoqueControllerUpdateMutationRequest = UpdateConferenciaEstoqueDto;

export type ConferenciaEstoqueControllerUpdateMutationResponse = ConferenciaEstoqueControllerUpdate200;

export type ConferenciaEstoqueControllerUpdateMutation = {
    Response: ConferenciaEstoqueControllerUpdate200;
    Request: ConferenciaEstoqueControllerUpdateMutationRequest;
    PathParams: ConferenciaEstoqueControllerUpdatePathParams;
    HeaderParams: ConferenciaEstoqueControllerUpdateHeaderParams;
    Errors: ConferenciaEstoqueControllerUpdate400 | ConferenciaEstoqueControllerUpdate404;
};