/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContasPagar } from './ContasPagar.ts'

export type ContasPagarControllerFindByParceiroPathParams = {
  /**
   * @description ID do parceiro
   * @type number
   */
  parceiroId: number
}

/**
 * @description Contas a pagar do parceiro.
 */
export type ContasPagarControllerFindByParceiro200 = ContasPagar[]

export type ContasPagarControllerFindByParceiroQueryResponse = ContasPagarControllerFindByParceiro200

export type ContasPagarControllerFindByParceiroQuery = {
  Response: ContasPagarControllerFindByParceiro200
  PathParams: ContasPagarControllerFindByParceiroPathParams
  Errors: any
}