/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ContasPagarParcelas } from './ContasPagarParcelas.ts'

export type ContasPagarParcelasControllerFindAllAgendaPathParams = {
  /**
   * @description ID do parceiro
   * @type integer, int64
   */
  parceiroId: number
}

/**
 * @description Lista de parcelas.
 */
export type ContasPagarParcelasControllerFindAllAgenda200 = ContasPagarParcelas[]

export type ContasPagarParcelasControllerFindAllAgendaQueryResponse = ContasPagarParcelasControllerFindAllAgenda200

export type ContasPagarParcelasControllerFindAllAgendaQuery = {
  Response: ContasPagarParcelasControllerFindAllAgenda200
  PathParams: ContasPagarParcelasControllerFindAllAgendaPathParams
  Errors: any
}
