/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ContaDRE } from "./ContaDRE.ts";
import type { UpdateContaDreDto } from "./UpdateContaDreDto.ts";

export type ContaDreControllerUpdatePathParams = {
    /**
     * @description ID da conta DRE
     * @type number
    */
    id: number;
};

export type ContaDreControllerUpdateHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Conta DRE atualizada com sucesso
*/
export type ContaDreControllerUpdate200 = ContaDRE;

/**
 * @description Não autorizado
*/
export type ContaDreControllerUpdate401 = any;

/**
 * @description Conta DRE não encontrada
*/
export type ContaDreControllerUpdate404 = any;

/**
 * @description Já existe uma conta com este nome neste grupo
*/
export type ContaDreControllerUpdate409 = any;

export type ContaDreControllerUpdateMutationRequest = UpdateContaDreDto;

export type ContaDreControllerUpdateMutationResponse = ContaDreControllerUpdate200;

export type ContaDreControllerUpdateMutation = {
    Response: ContaDreControllerUpdate200;
    Request: ContaDreControllerUpdateMutationRequest;
    PathParams: ContaDreControllerUpdatePathParams;
    HeaderParams: ContaDreControllerUpdateHeaderParams;
    Errors: ContaDreControllerUpdate401 | ContaDreControllerUpdate404 | ContaDreControllerUpdate409;
};