/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateProdutoSkuDto = {
    /**
     * @description ID do produto SKU
     * @type number
    */
    id: number;
    /**
     * @description ID do produto SKU
     * @type number
    */
    produtoId: number;
    /**
     * @description Cor do produto
     * @maxLength 50
     * @type string | undefined
    */
    cor?: string | undefined;
    /**
     * @description Código hexadecimal da cor
     * @type string | undefined
    */
    codCor?: string | undefined;
    /**
     * @description Tamanho do produto
     * @maxLength 10
     * @type string | undefined
    */
    tamanho?: string | undefined;
    /**
     * @description Quantidade mínima em estoque
     * @default 0
     * @type number
    */
    qtdMinima: number;
    /**
     * @description Data da última compra
     * @type string | undefined, date-time
    */
    dataUltimaCompra?: string | undefined;
};