/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const createDespesaDtoTipoPagamentoEnum = {
    "A_VISTA_IMEDIATA": "A_VISTA_IMEDIATA",
    "A_PRAZO_SEM_PARCELAS": "A_PRAZO_SEM_PARCELAS",
    "PARCELADO": "PARCELADO"
} as const;

export type CreateDespesaDtoTipoPagamentoEnumKey = (typeof createDespesaDtoTipoPagamentoEnum)[keyof typeof createDespesaDtoTipoPagamentoEnum];

export type CreateDespesaDto = {
    /**
     * @description Data do registro
     * @type string | undefined
    */
    dataRegistro?: string | undefined;
    /**
     * @description Valor da despesa
     * @type number
    */
    valorTotal: number;
    /**
     * @description Descrição da despesa
     * @type string
    */
    descricao: string;
    /**
     * @description ID da subcategoria da despesa
     * @type number
    */
    subCategoriaId: number;
    /**
     * @description ID do parceiro responsável pela despesa
     * @type number
    */
    parceiroId: number;
    /**
     * @description ID do fornecedor da despesa
     * @type number | undefined
    */
    fornecedorId?: number | undefined;
    /**
     * @description Tipo de pagamento da despesa
     * @type string
    */
    tipoPagamento: CreateDespesaDtoTipoPagamentoEnumKey;
    /**
     * @description Valor da entrada (apenas para pagamento parcelado)
     * @type number | undefined
    */
    valorEntrada?: number | undefined;
    /**
     * @description Data da primeira parcela (apenas para pagamento parcelado)
     * @type string | undefined
    */
    dataPrimeiraParcela?: string | undefined;
    /**
     * @description Número de parcelas (apenas para pagamento parcelado)
     * @type number | undefined
    */
    numeroParcelas?: number | undefined;
    /**
     * @description Data de vencimento (apenas para pagamento à prazo sem parcelas)
     * @type string | undefined
    */
    dataVencimento?: string | undefined;
    /**
     * @description ID da moeda da despesa
     * @type number | undefined
    */
    currencyId?: number | undefined;
    /**
     * @description Cotação da moeda no momento da despesa
     * @type number | undefined
    */
    cotacao?: number | undefined;
};