/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const createVendaItemDtoTipoEnum = {
    "NORMAL": "NORMAL",
    "BRINDE": "BRINDE"
} as const;

export type CreateVendaItemDtoTipoEnum = (typeof createVendaItemDtoTipoEnum)[keyof typeof createVendaItemDtoTipoEnum];

export type CreateVendaItemDto = {
    /**
     * @description ID da venda
     * @type number
    */
    vendaId: number;
    /**
     * @description ID do SKU
     * @type number
    */
    skuId: number;
    /**
     * @description Tipo do item
     * @type string | undefined
    */
    tipo?: CreateVendaItemDtoTipoEnum;
    /**
     * @description Quantidade reservada
     * @type number
    */
    qtdReservada: number;
    /**
     * @description Quantidade aceita (cliente ficou)
     * @type number | undefined
    */
    qtdAceita?: number;
    /**
     * @description Quantidade devolvida
     * @type number | undefined
    */
    qtdDevolvida?: number;
    /**
     * @description Desconto por item
     * @type number | undefined
    */
    desconto?: number;
    /**
     * @description Preço unitário
     * @type number
    */
    precoUnit: number;
};