/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CurrencyControllerRemovePathParams = {
    /**
     * @description ID público da moeda
     * @type string
    */
    publicId: string;
};

/**
 * @description Moeda removida com sucesso
*/
export type CurrencyControllerRemove200 = any;

/**
 * @description Não autorizado
*/
export type CurrencyControllerRemove401 = any;

/**
 * @description Moeda não encontrada
*/
export type CurrencyControllerRemove404 = any;

/**
 * @description Moeda está sendo utilizada e não pode ser removida
*/
export type CurrencyControllerRemove409 = any;

export type CurrencyControllerRemoveMutationResponse = CurrencyControllerRemove200;

export type CurrencyControllerRemoveMutation = {
    Response: CurrencyControllerRemove200;
    PathParams: CurrencyControllerRemovePathParams;
    Errors: CurrencyControllerRemove401 | CurrencyControllerRemove404 | CurrencyControllerRemove409;
};