/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DespesasControllerRemovePathParams = {
  /**
   * @description ID público da despesa
   * @type string
   */
  publicId: string
}

/**
 * @description Despesa removida com sucesso
 */
export type DespesasControllerRemove204 = any

/**
 * @description Despesa não encontrada
 */
export type DespesasControllerRemove404 = any

export type DespesasControllerRemoveMutationResponse = DespesasControllerRemove204

export type DespesasControllerRemoveMutation = {
  Response: DespesasControllerRemove204
  PathParams: DespesasControllerRemovePathParams
  Errors: DespesasControllerRemove404
}