/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DespesaRecorrente } from './DespesaRecorrente.ts'

export type DespesasRecorrentesControllerFindOnePathParams = {
  /**
   * @description ID público da despesa recorrente
   * @type string
   */
  publicId: string
}

/**
 * @description Despesa recorrente encontrada
 */
export type DespesasRecorrentesControllerFindOne200 = DespesaRecorrente

/**
 * @description Não autorizado
 */
export type DespesasRecorrentesControllerFindOne401 = any

/**
 * @description Despesa recorrente não encontrada
 */
export type DespesasRecorrentesControllerFindOne404 = any

export type DespesasRecorrentesControllerFindOneQueryResponse = DespesasRecorrentesControllerFindOne200

export type DespesasRecorrentesControllerFindOneQuery = {
  Response: DespesasRecorrentesControllerFindOne200
  PathParams: DespesasRecorrentesControllerFindOnePathParams
  Errors: DespesasRecorrentesControllerFindOne401 | DespesasRecorrentesControllerFindOne404
}
