/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ContaDRE } from "./ContaDRE.ts";
import type { Currency } from "./Currency.ts";
import type { Fornecedor } from "./Fornecedor.ts";
import type { SubCategoriaDespesa } from "./SubCategoriaDespesa.ts";

export type Despesa = {
    /**
     * @description ID único da despesa
     * @type number
    */
    id: number;
    /**
     * @description ID público da despesa
     * @type string
    */
    publicId: string;
    /**
     * @description Data de registro da despesa
     * @type string, date-time
    */
    dataRegistro: string;
    /**
     * @description Valor total da despesa
     * @type number
    */
    valorTotal: number;
    /**
     * @description Descrição da despesa
     * @type string
    */
    descricao: string;
    /**
     * @description ID da subcategoria da despesa
     * @type number
    */
    subCategoriaId: number;
    /**
     * @description ID do parceiro responsável pela despesa
     * @type number
    */
    parceiroId: number;
    /**
     * @description ID do fornecedor da despesa
     * @type number | undefined
    */
    fornecedorId?: number | undefined;
    /**
     * @description ID da moeda da despesa
     * @type number | undefined
    */
    currencyId?: number | undefined;
    /**
     * @description Cotação da moeda no momento da despesa
     * @type number | undefined
    */
    cotacao?: number | undefined;
    /**
     * @description Fornecedor da despesa
    */
    fornecedor?: Fornecedor | undefined;
    /**
     * @description Subcategoria da despesa
    */
    subCategoria: SubCategoriaDespesa;
    /**
     * @description Moeda da despesa
    */
    currency?: Currency | undefined;
    /**
     * @description ID da conta DRE para classificação contábil
     * @type number | undefined
    */
    contaDreId?: number | undefined;
    /**
     * @description Conta DRE da despesa
    */
    contaDre?: ContaDRE | undefined;
};