/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateEstoqueSkuDto } from "./CreateEstoqueSkuDto.ts";
import type { EstoqueSku } from "./EstoqueSku.ts";

/**
 * @description Registro de estoque criado com sucesso
*/
export type EstoqueSkuControllerCreate201 = EstoqueSku;

/**
 * @description Dados inválidos
*/
export type EstoqueSkuControllerCreate400 = any;

/**
 * @description SKU ou local não encontrado
*/
export type EstoqueSkuControllerCreate404 = any;

/**
 * @description Já existe registro de estoque para este SKU neste local
*/
export type EstoqueSkuControllerCreate409 = any;

/**
 * @description Dados para criação do registro de estoque
*/
export type EstoqueSkuControllerCreateMutationRequest = CreateEstoqueSkuDto;

export type EstoqueSkuControllerCreateMutationResponse = EstoqueSkuControllerCreate201;

export type EstoqueSkuControllerCreateMutation = {
    Response: EstoqueSkuControllerCreate201;
    Request: EstoqueSkuControllerCreateMutationRequest;
    Errors: EstoqueSkuControllerCreate400 | EstoqueSkuControllerCreate404 | EstoqueSkuControllerCreate409;
};