/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EstoqueSku } from "./EstoqueSku.ts";

export type EstoqueSkuControllerFindByLocalPathParams = {
    /**
     * @description ID do local de estoque
     * @type number
    */
    localId: number;
};

/**
 * @description Lista de estoque do local retornada com sucesso
*/
export type EstoqueSkuControllerFindByLocal200 = EstoqueSku[];

export type EstoqueSkuControllerFindByLocalQueryResponse = EstoqueSkuControllerFindByLocal200;

export type EstoqueSkuControllerFindByLocalQuery = {
    Response: EstoqueSkuControllerFindByLocal200;
    PathParams: EstoqueSkuControllerFindByLocalPathParams;
    Errors: any;
};