/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Fornecedor = {
    /**
     * @description ID único do fornecedor
     * @type number
    */
    id: number;
    /**
     * @description ID público do fornecedor
     * @type string
    */
    publicId: string;
    /**
     * @description ID do parceiro do fornecedor
     * @type number
    */
    parceiroId: number;
    /**
     * @description Nome do fornecedor
     * @type string
    */
    nome: string;
    /**
     * @description RUC/CNPJ do fornecedor
     * @type string | undefined
    */
    ruccnpj?: string;
    /**
     * @description Email do fornecedor
     * @type string | undefined
    */
    email?: string;
    /**
     * @description Telefone do fornecedor
     * @type string | undefined
    */
    telefone?: string;
    /**
     * @description Rede social do fornecedor
     * @type string | undefined
    */
    redesocial?: string;
    /**
     * @description Status ativo do fornecedor
     * @type boolean
    */
    ativo: boolean;
    /**
     * @description Data da última compra
     * @type string | undefined, date-time
    */
    ultimaCompra?: string;
    /**
     * @description Data de criação do fornecedor
     * @type string, date-time
    */
    createdAt: string;
};