/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Fornecedor } from "./Fornecedor.ts";

export type FornecedoresControllerActivateFornecedorPathParams = {
    /**
     * @description ID público do fornecedor (UUID v7)
     * @type string
    */
    publicId: string;
};

export type FornecedoresControllerActivateFornecedorHeaderParams = {
    /**
     * @description ID do parceiro
     * @type string
    */
    "x-parceiro-id": string;
};

/**
 * @description Fornecedor ativado com sucesso
*/
export type FornecedoresControllerActivateFornecedor200 = Fornecedor;

/**
 * @description Header x-parceiro-id é obrigatório
*/
export type FornecedoresControllerActivateFornecedor400 = any;

/**
 * @description Fornecedor não encontrado
*/
export type FornecedoresControllerActivateFornecedor404 = any;

export type FornecedoresControllerActivateFornecedorMutationResponse = FornecedoresControllerActivateFornecedor200;

export type FornecedoresControllerActivateFornecedorMutation = {
    Response: FornecedoresControllerActivateFornecedor200;
    PathParams: FornecedoresControllerActivateFornecedorPathParams;
    HeaderParams: FornecedoresControllerActivateFornecedorHeaderParams;
    Errors: FornecedoresControllerActivateFornecedor400 | FornecedoresControllerActivateFornecedor404;
};