/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Fornecedor } from "./Fornecedor.ts";

export type FornecedoresControllerFindAllPathParams = {
    /**
     * @description ID do parceiro
     * @type number
    */
    parceiroId: number;
};

/**
 * @description Lista de fornecedores retornada com sucesso
*/
export type FornecedoresControllerFindAll200 = Fornecedor[];

export type FornecedoresControllerFindAllQueryResponse = FornecedoresControllerFindAll200;

export type FornecedoresControllerFindAllQuery = {
    Response: FornecedoresControllerFindAll200;
    PathParams: FornecedoresControllerFindAllPathParams;
    Errors: any;
};