/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GrupoDRE } from "./GrupoDRE.ts";
import type { UpdateGrupoDreDto } from "./UpdateGrupoDreDto.ts";

export type GrupoDreControllerUpdatePathParams = {
    /**
     * @description ID do grupo DRE
     * @type number
    */
    id: number;
};

/**
 * @description Grupo DRE atualizado com sucesso
*/
export type GrupoDreControllerUpdate200 = GrupoDRE;

/**
 * @description Não autorizado
*/
export type GrupoDreControllerUpdate401 = any;

/**
 * @description Grupo DRE não encontrado
*/
export type GrupoDreControllerUpdate404 = any;

/**
 * @description Código do grupo DRE já está em uso
*/
export type GrupoDreControllerUpdate409 = any;

export type GrupoDreControllerUpdateMutationRequest = UpdateGrupoDreDto;

export type GrupoDreControllerUpdateMutationResponse = GrupoDreControllerUpdate200;

export type GrupoDreControllerUpdateMutation = {
    Response: GrupoDreControllerUpdate200;
    Request: GrupoDreControllerUpdateMutationRequest;
    PathParams: GrupoDreControllerUpdatePathParams;
    Errors: GrupoDreControllerUpdate401 | GrupoDreControllerUpdate404 | GrupoDreControllerUpdate409;
};