/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Imposto } from "./Imposto.ts";
import type { UpdateImpostoDto } from "./UpdateImpostoDto.ts";

export type ImpostoControllerUpdatePathParams = {
    /**
     * @description ID do imposto
     * @type number
    */
    id: number;
};

export type ImpostoControllerUpdateHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Imposto atualizado com sucesso
*/
export type ImpostoControllerUpdate200 = Imposto;

/**
 * @description Não autorizado
*/
export type ImpostoControllerUpdate401 = any;

/**
 * @description Imposto não encontrado
*/
export type ImpostoControllerUpdate404 = any;

/**
 * @description Já existe um imposto com esta sigla para este parceiro
*/
export type ImpostoControllerUpdate409 = any;

export type ImpostoControllerUpdateMutationRequest = UpdateImpostoDto;

export type ImpostoControllerUpdateMutationResponse = ImpostoControllerUpdate200;

export type ImpostoControllerUpdateMutation = {
    Response: ImpostoControllerUpdate200;
    Request: ImpostoControllerUpdateMutationRequest;
    PathParams: ImpostoControllerUpdatePathParams;
    HeaderParams: ImpostoControllerUpdateHeaderParams;
    Errors: ImpostoControllerUpdate401 | ImpostoControllerUpdate404 | ImpostoControllerUpdate409;
};