/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type LocalEstoque = {
    /**
     * @description ID único do local de estoque
     * @type number
    */
    id: number;
    /**
     * @description ID público do local de estoque
     * @type string
    */
    publicId: string;
    /**
     * @description ID do parceiro proprietário
     * @type number
    */
    parceiroId: number;
    /**
     * @description Nome do local de estoque
     * @type string
    */
    nome: string;
    /**
     * @description Descrição do local de estoque
     * @type string
    */
    descricao: string;
    /**
     * @description Endereço do local de estoque
     * @type string
    */
    endereco: string;
};