/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type LocalEstoqueResponseDto = {
    /**
     * @description ID do local
     * @type number
    */
    id: number;
    /**
     * @description Public ID do local
     * @type string
    */
    publicId: string;
    /**
     * @description Nome do local
     * @type string
    */
    nome: string;
    /**
     * @description Descrição do local
     * @type string
    */
    descricao: string;
};