/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AjusteConferenciaLoteDto } from "./AjusteConferenciaLoteDto.ts";

/**
 * @description Ajustes processados com sucesso
*/
export type MovimentoEstoqueControllerProcessarAjustesConferenciaLote201 = {
    /**
     * @type number | undefined
    */
    totalProcessados?: number | undefined;
    /**
     * @type number | undefined
    */
    totalIgnorados?: number | undefined;
};

/**
 * @description Dados inválidos ou lista vazia
*/
export type MovimentoEstoqueControllerProcessarAjustesConferenciaLote400 = any;

/**
 * @description SKU ou local não encontrado
*/
export type MovimentoEstoqueControllerProcessarAjustesConferenciaLote404 = any;

/**
 * @description Estoque insuficiente para ajuste negativo
*/
export type MovimentoEstoqueControllerProcessarAjustesConferenciaLote409 = any;

export type MovimentoEstoqueControllerProcessarAjustesConferenciaLoteMutationRequest = AjusteConferenciaLoteDto;

export type MovimentoEstoqueControllerProcessarAjustesConferenciaLoteMutationResponse = MovimentoEstoqueControllerProcessarAjustesConferenciaLote201;

export type MovimentoEstoqueControllerProcessarAjustesConferenciaLoteMutation = {
    Response: MovimentoEstoqueControllerProcessarAjustesConferenciaLote201;
    Request: MovimentoEstoqueControllerProcessarAjustesConferenciaLoteMutationRequest;
    Errors: MovimentoEstoqueControllerProcessarAjustesConferenciaLote400 | MovimentoEstoqueControllerProcessarAjustesConferenciaLote404 | MovimentoEstoqueControllerProcessarAjustesConferenciaLote409;
};