/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProdutoSKU } from "./ProdutoSKU.ts";

export type PaginatedProdutoSkuResponseDto = {
    /**
     * @description Lista de SKUs
     * @type array
    */
    data: ProdutoSKU[];
    /**
     * @description Total de registros
     * @type number
    */
    total: number;
    /**
     * @description Página atual
     * @type number
    */
    page: number;
    /**
     * @description Limite de registros por página
     * @type number
    */
    limit: number;
    /**
     * @description Total de páginas
     * @type number
    */
    totalPages: number;
};