/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MovimentoEstoqueResponseDto } from "./MovimentoEstoqueResponseDto.ts";

export type PaginatedMovimentoEstoqueResponseDto = {
    /**
     * @description Lista de movimentos de estoque
     * @type array
    */
    data: MovimentoEstoqueResponseDto[];
    /**
     * @description Total de registros
     * @type number
    */
    total: number;
    /**
     * @description Página atual
     * @type number
    */
    page: number;
    /**
     * @description Limite de registros por página
     * @type number
    */
    limit: number;
    /**
     * @description Total de páginas
     * @type number
    */
    totalPages: number;
};