/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Parceiro } from "./Parceiro.ts";

export type PaginatedParceiroResponseDto = {
    /**
     * @description Lista de parceiros
     * @type array
    */
    data: Parceiro[];
    /**
     * @description Total de registros
     * @type number
    */
    total: number;
    /**
     * @description Página atual
     * @type number
    */
    page: number;
    /**
     * @description Limite de registros por página
     * @type number
    */
    limit: number;
    /**
     * @description Total de páginas
     * @type number
    */
    totalPages: number;
};