/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Parceiro } from './Parceiro.ts'

export type ParceirosControllerActivateParceiroPathParams = {
  /**
   * @description ID público do parceiro
   * @type string
   */
  publicId: string
}

/**
 * @description Parceiro ativado com sucesso
 */
export type ParceirosControllerActivateParceiro200 = Parceiro

/**
 * @description Parceiro não encontrado
 */
export type ParceirosControllerActivateParceiro404 = any

export type ParceirosControllerActivateParceiroMutationResponse = ParceirosControllerActivateParceiro200

export type ParceirosControllerActivateParceiroMutation = {
  Response: ParceirosControllerActivateParceiro200
  PathParams: ParceirosControllerActivateParceiroPathParams
  Errors: ParceirosControllerActivateParceiro404
}