/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PedidoCompraControllerRemovePathParams = {
    /**
     * @description ID público do pedido de compra (UUID v7)
     * @type string
    */
    publicId: string;
};

export type PedidoCompraControllerRemoveHeaderParams = {
    /**
     * @description ID do parceiro
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Pedido de compra removido com sucesso
*/
export type PedidoCompraControllerRemove200 = any;

/**
 * @description Pedido de compra não encontrado
*/
export type PedidoCompraControllerRemove404 = any;

/**
 * @description Não é possível remover um pedido finalizado
*/
export type PedidoCompraControllerRemove409 = any;

export type PedidoCompraControllerRemoveMutationResponse = PedidoCompraControllerRemove200;

export type PedidoCompraControllerRemoveMutation = {
    Response: PedidoCompraControllerRemove200;
    PathParams: PedidoCompraControllerRemovePathParams;
    HeaderParams: PedidoCompraControllerRemoveHeaderParams;
    Errors: PedidoCompraControllerRemove404 | PedidoCompraControllerRemove409;
};