/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProdutoSKU } from "./ProdutoSKU.ts";

export type ProdutoSkuControllerFindAllHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Lista de SKUs de produtos
*/
export type ProdutoSkuControllerFindAll200 = ProdutoSKU[];

export type ProdutoSkuControllerFindAllQueryResponse = ProdutoSkuControllerFindAll200;

export type ProdutoSkuControllerFindAllQuery = {
    Response: ProdutoSkuControllerFindAll200;
    HeaderParams: ProdutoSkuControllerFindAllHeaderParams;
    Errors: any;
};