/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateProdutoDto } from "./CreateProdutoDto.ts";
import type { Produto } from "./Produto.ts";

export type ProdutoControllerCreateHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Produto criado com sucesso
*/
export type ProdutoControllerCreate201 = Produto;

/**
 * @description Dados inválidos
*/
export type ProdutoControllerCreate400 = any;

/**
 * @description Nome do produto já está em uso nesta organização
*/
export type ProdutoControllerCreate409 = any;

export type ProdutoControllerCreateMutationRequest = CreateProdutoDto;

export type ProdutoControllerCreateMutationResponse = ProdutoControllerCreate201;

export type ProdutoControllerCreateMutation = {
    Response: ProdutoControllerCreate201;
    Request: ProdutoControllerCreateMutationRequest;
    HeaderParams: ProdutoControllerCreateHeaderParams;
    Errors: ProdutoControllerCreate400 | ProdutoControllerCreate409;
};