/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Produto } from "./Produto.ts";
import type { UpdateProdutoDto } from "./UpdateProdutoDto.ts";

export type ProdutoControllerUpdatePathParams = {
    /**
     * @description ID público do produto
     * @type string
    */
    publicId: string;
};

export type ProdutoControllerUpdateHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Produto atualizado com sucesso
*/
export type ProdutoControllerUpdate200 = Produto;

/**
 * @description Dados inválidos
*/
export type ProdutoControllerUpdate400 = any;

/**
 * @description Produto não encontrado
*/
export type ProdutoControllerUpdate404 = any;

/**
 * @description Nome do produto já está em uso nesta organização
*/
export type ProdutoControllerUpdate409 = any;

export type ProdutoControllerUpdateMutationRequest = UpdateProdutoDto;

export type ProdutoControllerUpdateMutationResponse = ProdutoControllerUpdate200;

export type ProdutoControllerUpdateMutation = {
    Response: ProdutoControllerUpdate200;
    Request: ProdutoControllerUpdateMutationRequest;
    PathParams: ProdutoControllerUpdatePathParams;
    HeaderParams: ProdutoControllerUpdateHeaderParams;
    Errors: ProdutoControllerUpdate400 | ProdutoControllerUpdate404 | ProdutoControllerUpdate409;
};