/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Produto } from "./Produto.ts";

export type ProdutoControllerActivatePathParams = {
    /**
     * @description ID público do produto
     * @type string
    */
    publicId: string;
};

export type ProdutoControllerActivateHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Produto ativado com sucesso
*/
export type ProdutoControllerActivate200 = Produto;

/**
 * @description Produto não encontrado
*/
export type ProdutoControllerActivate404 = any;

export type ProdutoControllerActivateMutationResponse = ProdutoControllerActivate200;

export type ProdutoControllerActivateMutation = {
    Response: ProdutoControllerActivate200;
    PathParams: ProdutoControllerActivatePathParams;
    HeaderParams: ProdutoControllerActivateHeaderParams;
    Errors: ProdutoControllerActivate404;
};