/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateProdutoHistoricoPrecoDto } from "./CreateProdutoHistoricoPrecoDto.ts";
import type { ProdutoHistoricoPreco } from "./ProdutoHistoricoPreco.ts";

export type ProdutoHistoricoPrecoControllerCreateHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Histórico de preço criado com sucesso
*/
export type ProdutoHistoricoPrecoControllerCreate201 = ProdutoHistoricoPreco;

/**
 * @description Dados inválidos
*/
export type ProdutoHistoricoPrecoControllerCreate400 = any;

/**
 * @description Produto não encontrado
*/
export type ProdutoHistoricoPrecoControllerCreate404 = any;

export type ProdutoHistoricoPrecoControllerCreateMutationRequest = CreateProdutoHistoricoPrecoDto;

export type ProdutoHistoricoPrecoControllerCreateMutationResponse = ProdutoHistoricoPrecoControllerCreate201;

export type ProdutoHistoricoPrecoControllerCreateMutation = {
    Response: ProdutoHistoricoPrecoControllerCreate201;
    Request: ProdutoHistoricoPrecoControllerCreateMutationRequest;
    HeaderParams: ProdutoHistoricoPrecoControllerCreateHeaderParams;
    Errors: ProdutoHistoricoPrecoControllerCreate400 | ProdutoHistoricoPrecoControllerCreate404;
};