/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProdutoHistoricoPrecoResponseDto } from "./ProdutoHistoricoPrecoResponseDto.ts";

export type ProdutoHistoricoPrecoControllerFindByProdutoPublicIdPathParams = {
    /**
     * @description Public ID do produto
     * @type string
    */
    produtoPublicId: string;
};

export type ProdutoHistoricoPrecoControllerFindByProdutoPublicIdQueryParams = {
    /**
     * @description Data inicial para filtro (formato ISO)
     * @type string | undefined
    */
    dataInicial?: string;
    /**
     * @description Data final para filtro (formato ISO)
     * @type string | undefined
    */
    dataFinal?: string;
    /**
     * @description Limite de registros (máximo 100)
     * @minLength 1
     * @maxLength 100
     * @type integer | undefined
    */
    limit?: number;
};

export type ProdutoHistoricoPrecoControllerFindByProdutoPublicIdHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Lista de históricos de preço do produto
*/
export type ProdutoHistoricoPrecoControllerFindByProdutoPublicId200 = ProdutoHistoricoPrecoResponseDto[];

/**
 * @description Produto não encontrado
*/
export type ProdutoHistoricoPrecoControllerFindByProdutoPublicId404 = any;

export type ProdutoHistoricoPrecoControllerFindByProdutoPublicIdQueryResponse = ProdutoHistoricoPrecoControllerFindByProdutoPublicId200;

export type ProdutoHistoricoPrecoControllerFindByProdutoPublicIdQuery = {
    Response: ProdutoHistoricoPrecoControllerFindByProdutoPublicId200;
    PathParams: ProdutoHistoricoPrecoControllerFindByProdutoPublicIdPathParams;
    QueryParams: ProdutoHistoricoPrecoControllerFindByProdutoPublicIdQueryParams;
    HeaderParams: ProdutoHistoricoPrecoControllerFindByProdutoPublicIdHeaderParams;
    Errors: ProdutoHistoricoPrecoControllerFindByProdutoPublicId404;
};