/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RollupControllerGetYearSummaryQueryParams = {
    /**
     * @type string
    */
    parceiroId: string;
    /**
     * @type string
    */
    year: string;
};

export type RollupControllerGetYearSummary200 = any;

export type RollupControllerGetYearSummaryQueryResponse = RollupControllerGetYearSummary200;

export type RollupControllerGetYearSummaryQuery = {
    Response: RollupControllerGetYearSummary200;
    QueryParams: RollupControllerGetYearSummaryQueryParams;
    Errors: any;
};