/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type SubCategoriaDespesaControllerFindOnePathParams = {
    /**
     * @description ID da subcategoria de despesas
     * @type number
    */
    id: number;
};

/**
 * @description Subcategoria de despesas encontrada
*/
export type SubCategoriaDespesaControllerFindOne200 = {
    /**
     * @type number | undefined
    */
    idSubCategoria?: number | undefined;
    /**
     * @type number | undefined
    */
    categoriaId?: number | undefined;
    /**
     * @type string | undefined
    */
    descricao?: string | undefined;
    /**
     * @type boolean | undefined
    */
    ativo?: boolean | undefined;
    /**
     * @type string | undefined
    */
    createdAt?: string | undefined;
    /**
     * @type object | undefined
    */
    categoria?: {
        /**
         * @type number | undefined
        */
        idCategoria?: number | undefined;
        /**
         * @type string | undefined
        */
        descricao?: string | undefined;
        /**
         * @type boolean | undefined
        */
        ativo?: boolean | undefined;
    } | undefined;
};

/**
 * @description Não autorizado
*/
export type SubCategoriaDespesaControllerFindOne401 = any;

/**
 * @description Subcategoria de despesas não encontrada
*/
export type SubCategoriaDespesaControllerFindOne404 = any;

export type SubCategoriaDespesaControllerFindOneQueryResponse = SubCategoriaDespesaControllerFindOne200;

export type SubCategoriaDespesaControllerFindOneQuery = {
    Response: SubCategoriaDespesaControllerFindOne200;
    PathParams: SubCategoriaDespesaControllerFindOnePathParams;
    Errors: SubCategoriaDespesaControllerFindOne401 | SubCategoriaDespesaControllerFindOne404;
};