/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SubCategoriaDespesaControllerFindByCategoriaPathParams = {
  /**
   * @description ID da categoria de despesas
   * @type number
   */
  categoriaId: number
}

/**
 * @description Lista de subcategorias da categoria retornada com sucesso
 */
export type SubCategoriaDespesaControllerFindByCategoria200 = {
  /**
   * @type number | undefined
   */
  idSubCategoria?: number
  /**
   * @type number | undefined
   */
  categoriaId?: number
  /**
   * @type string | undefined
   */
  descricao?: string
  /**
   * @type boolean | undefined
   */
  ativo?: boolean
  /**
   * @type string | undefined
   */
  createdAt?: string
  /**
   * @type object | undefined
   */
  categoria?: {
    /**
     * @type number | undefined
     */
    idCategoria?: number
    /**
     * @type string | undefined
     */
    descricao?: string
    /**
     * @type boolean | undefined
     */
    ativo?: boolean
  }
}[]

/**
 * @description Não autorizado
 */
export type SubCategoriaDespesaControllerFindByCategoria401 = any

export type SubCategoriaDespesaControllerFindByCategoriaQueryResponse = SubCategoriaDespesaControllerFindByCategoria200

export type SubCategoriaDespesaControllerFindByCategoriaQuery = {
  Response: SubCategoriaDespesaControllerFindByCategoria200
  PathParams: SubCategoriaDespesaControllerFindByCategoriaPathParams
  Errors: SubCategoriaDespesaControllerFindByCategoria401
}
