/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateSubCategoriaDespesaDto } from "./UpdateSubCategoriaDespesaDto.ts";

export type SubCategoriaDespesaControllerUpdatePathParams = {
    /**
     * @description ID da subcategoria de despesas
     * @type number
    */
    id: number;
};

/**
 * @description Subcategoria de despesas atualizada com sucesso
*/
export type SubCategoriaDespesaControllerUpdate200 = {
    /**
     * @type number | undefined
    */
    idSubCategoria?: number;
    /**
     * @type number | undefined
    */
    categoriaId?: number;
    /**
     * @type string | undefined
    */
    descricao?: string;
    /**
     * @type boolean | undefined
    */
    ativo?: boolean;
    /**
     * @type string | undefined
    */
    createdAt?: string;
    /**
     * @type object | undefined
    */
    categoria?: {
        /**
         * @type number | undefined
        */
        idCategoria?: number;
        /**
         * @type string | undefined
        */
        descricao?: string;
        /**
         * @type boolean | undefined
        */
        ativo?: boolean;
    };
};

/**
 * @description Não autorizado
*/
export type SubCategoriaDespesaControllerUpdate401 = any;

/**
 * @description Subcategoria de despesas não encontrada
*/
export type SubCategoriaDespesaControllerUpdate404 = any;

/**
 * @description Descrição da subcategoria já existe nesta categoria
*/
export type SubCategoriaDespesaControllerUpdate409 = any;

export type SubCategoriaDespesaControllerUpdateMutationRequest = UpdateSubCategoriaDespesaDto;

export type SubCategoriaDespesaControllerUpdateMutationResponse = SubCategoriaDespesaControllerUpdate200;

export type SubCategoriaDespesaControllerUpdateMutation = {
    Response: SubCategoriaDespesaControllerUpdate200;
    Request: SubCategoriaDespesaControllerUpdateMutationRequest;
    PathParams: SubCategoriaDespesaControllerUpdatePathParams;
    Errors: SubCategoriaDespesaControllerUpdate401 | SubCategoriaDespesaControllerUpdate404 | SubCategoriaDespesaControllerUpdate409;
};