/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TransferenciaSkuSimplesDto } from "./TransferenciaSkuSimplesDto.ts";

export type TransferenciaEstoqueSkuControllerFindByTransferenciaPathParams = {
    /**
     * @description Public ID da transferência
     * @type string
    */
    transferenciaPublicId: string;
};

/**
 * @description Lista de SKUs da transferência retornada com sucesso
*/
export type TransferenciaEstoqueSkuControllerFindByTransferencia200 = TransferenciaSkuSimplesDto[];

/**
 * @description Transferência não encontrada
*/
export type TransferenciaEstoqueSkuControllerFindByTransferencia404 = any;

export type TransferenciaEstoqueSkuControllerFindByTransferenciaQueryResponse = TransferenciaEstoqueSkuControllerFindByTransferencia200;

export type TransferenciaEstoqueSkuControllerFindByTransferenciaQuery = {
    Response: TransferenciaEstoqueSkuControllerFindByTransferencia200;
    PathParams: TransferenciaEstoqueSkuControllerFindByTransferenciaPathParams;
    Errors: TransferenciaEstoqueSkuControllerFindByTransferencia404;
};