/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TransferenciaEstoqueControllerRemovePathParams = {
    /**
     * @description ID da transferência
     * @type string
    */
    id: string;
};

/**
 * @description Transferência excluída com sucesso
*/
export type TransferenciaEstoqueControllerRemove200 = any;

/**
 * @description Transferência não encontrada
*/
export type TransferenciaEstoqueControllerRemove404 = any;

/**
 * @description Não é possível excluir uma transferência já recebida
*/
export type TransferenciaEstoqueControllerRemove409 = any;

export type TransferenciaEstoqueControllerRemoveMutationResponse = TransferenciaEstoqueControllerRemove200;

export type TransferenciaEstoqueControllerRemoveMutation = {
    Response: TransferenciaEstoqueControllerRemove200;
    PathParams: TransferenciaEstoqueControllerRemovePathParams;
    Errors: TransferenciaEstoqueControllerRemove404 | TransferenciaEstoqueControllerRemove409;
};