/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateSubCategoriaDespesaDto = {
    /**
     * @description ID da subcategoria de despesa
     * @type number
    */
    idSubCategoria?: (number | null) | undefined;
    /**
     * @description ID da categoria de despesa
     * @type number | undefined
    */
    categoriaId?: number | undefined;
    /**
     * @description Descrição da subcategoria de despesa
     * @type string | undefined
    */
    descricao?: string | undefined;
    /**
     * @description Status ativo da subcategoria
     * @type boolean
    */
    ativo?: (boolean | null) | undefined;
};