/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const updateGrupoDreDtoTipoEnum = {
    "RECEITA": "RECEITA",
    "DEDUCAO": "DEDUCAO",
    "CUSTO": "CUSTO",
    "DESPESA": "DESPESA"
} as const;

export type UpdateGrupoDreDtoTipoEnumKey = (typeof updateGrupoDreDtoTipoEnum)[keyof typeof updateGrupoDreDtoTipoEnum];

export type UpdateGrupoDreDto = {
    /**
     * @description Código do grupo DRE (ex: 1000, 2000)
     * @type string | undefined
    */
    codigo?: string | undefined;
    /**
     * @description Nome do grupo DRE
     * @type string | undefined
    */
    nome?: string | undefined;
    /**
     * @description Tipo do grupo DRE
     * @type string | undefined
    */
    tipo?: UpdateGrupoDreDtoTipoEnumKey | undefined;
    /**
     * @description Ordem de exibição na DRE
     * @type number | undefined
    */
    ordem?: number | undefined;
    /**
     * @description Status ativo do grupo
     * @type boolean | undefined
    */
    ativo?: boolean | undefined;
};