/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateCanalOrigemDto = {
  /**
   * @description Nome do canal de origem
   * @type string | undefined
   */
  nome?: string
  /**
   * @description Descrição do canal de origem
   * @type string | undefined
   */
  descricao?: string
  /**
   * @description Status ativo do canal de origem
   * @default true
   * @type boolean | undefined
   */
  ativo?: boolean
}