/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const updatePagamentoDtoTipoEnum = {
    "A_VISTA_IMEDIATA": "A_VISTA_IMEDIATA",
    "A_PRAZO_SEM_PARCELAS": "A_PRAZO_SEM_PARCELAS",
    "PARCELADO": "PARCELADO",
    "PARCELADO_FLEXIVEL": "PARCELADO_FLEXIVEL"
} as const;

export type UpdatePagamentoDtoTipoEnumKey = (typeof updatePagamentoDtoTipoEnum)[keyof typeof updatePagamentoDtoTipoEnum];

export type UpdatePagamentoDto = {
    /**
     * @description ID da venda
     * @type number | undefined
    */
    vendaId?: number;
    /**
     * @description ID da forma de pagamento
     * @type number | undefined
    */
    formaPagamentoId?: number;
    /**
     * @description Tipo da venda
     * @type string | undefined
    */
    tipo?: UpdatePagamentoDtoTipoEnumKey;
    /**
     * @description Valor pago
     * @type number | undefined
    */
    valor?: number;
    /**
     * @description Valor do delivery, se houver
     * @type number | undefined
    */
    valorDelivery?: number;
    /**
     * @description É pagamento de entrada?
     * @default false
     * @type boolean | undefined
    */
    entrada?: boolean;
};