/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateCategoriaProdutoDto = {
    /**
     * @description Descrição da categoria do produto
     * @maxLength 255
     * @type string | undefined
    */
    descricao?: string;
};