/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateContasPagarParcelasDto = {
  /**
   * @description Data do pagamento da parcela
   * @type string | undefined
   */
  dataPagamento?: string
  /**
   * @description Data de vencimento da parcela
   * @type string | undefined
   */
  dataVencimento?: string
  /**
   * @description Valor da parcela
   * @type number | undefined
   */
  valor?: number
  /**
   * @description Se a parcela foi paga
   * @type boolean | undefined
   */
  pago?: boolean
  /**
   * @description ID da conta a pagar relacionada
   * @type number | undefined
   */
  contasPagarId?: number
}