/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateTransferenciaEstoqueSkuDto = {
    /**
     * @description ID da transferência de estoque
     * @type number | undefined
    */
    transferenciaId?: number;
    /**
     * @description ID do movimento de estoque
     * @type number | undefined
    */
    movimentoEstoqueId?: number;
};