/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const updateConferenciaEstoqueDtoStatusEnum = {
    "PENDENTE": "PENDENTE",
    "EM_ANDAMENTO": "EM_ANDAMENTO",
    "CONCLUIDA": "CONCLUIDA",
    "FINALIZADA": "FINALIZADA",
    "CANCELADA": "CANCELADA"
} as const;

export type UpdateConferenciaEstoqueDtoStatusEnumKey = (typeof updateConferenciaEstoqueDtoStatusEnum)[keyof typeof updateConferenciaEstoqueDtoStatusEnum];

export type UpdateConferenciaEstoqueDto = {
    /**
     * @description ID do local de estoque
     * @type number | undefined
    */
    localEstoqueId?: number;
    /**
     * @description ID do usuário responsável pela conferência
     * @type number | undefined
    */
    usuarioResponsavel?: number;
    /**
     * @description Data de início da conferência
     * @type string | undefined
    */
    dataInicio?: string;
    /**
     * @description Data de fim da conferência
     * @type string | undefined
    */
    dataFim?: string;
    /**
     * @description Status da conferência
     * @default "PENDENTE"
     * @type string | undefined
    */
    status?: UpdateConferenciaEstoqueDtoStatusEnumKey;
};