/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const updateDespesaRecorrenteDtoFrequenciaEnum = {
    "SEMANAL": "SEMANAL",
    "QUINZENAL": "QUINZENAL",
    "MENSAL": "MENSAL",
    "TRIMESTRAL": "TRIMESTRAL",
    "SEMESTRAL": "SEMESTRAL",
    "ANUAL": "ANUAL"
} as const;

export type UpdateDespesaRecorrenteDtoFrequenciaEnum = (typeof updateDespesaRecorrenteDtoFrequenciaEnum)[keyof typeof updateDespesaRecorrenteDtoFrequenciaEnum];

export type UpdateDespesaRecorrenteDto = {
    /**
     * @description Descrição da despesa recorrente
     * @type string | undefined
    */
    descricao?: string;
    /**
     * @description Valor da despesa recorrente
     * @type number | undefined
    */
    valor?: number;
    /**
     * @description Frequência da despesa recorrente
     * @type string | undefined
    */
    frequencia?: UpdateDespesaRecorrenteDtoFrequenciaEnum;
    /**
     * @description Dia do vencimento da despesa recorrente (1-31)
     * @type number | undefined
    */
    diaVencimento?: number;
    /**
     * @description Data de início da despesa recorrente
     * @type string | undefined
    */
    dataInicio?: string;
    /**
     * @description Data de fim da despesa recorrente
     * @type string | undefined
    */
    dataFim?: string;
    /**
     * @description ID da subcategoria da despesa
     * @type number | undefined
    */
    subCategoriaId?: number;
    /**
     * @description ID do parceiro responsável pela despesa
     * @type number | undefined
    */
    parceiroId?: number;
    /**
     * @description ID do fornecedor da despesa
     * @type number | undefined
    */
    fornecedorId?: number;
    /**
     * @description ID da moeda da despesa
     * @type number | undefined
    */
    currencyId?: number;
    /**
     * @description Cotação da moeda no momento da despesa
     * @type number | undefined
    */
    cotacao?: number;
};