/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdatePedidoCompraItemDto = {
    /**
     * @description ID do pedido de compra
     * @type number | undefined
    */
    pedidoCompraId?: number | undefined;
    /**
     * @description ID do SKU do produto
     * @type number | undefined
    */
    skuId?: number | undefined;
    /**
     * @description Quantidade do item
     * @type number | undefined
    */
    qtd?: number | undefined;
    /**
     * @description Preço de compra unitário
     * @type number | undefined
    */
    precoCompra?: number | undefined;
    /**
     * @description Observações do item
     * @type string | undefined
    */
    observacao?: string | undefined;
};