/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateImpostoDto = {
    /**
     * @description Nome do imposto
     * @type string | undefined
    */
    nome?: string | undefined;
    /**
     * @description Sigla do imposto
     * @type string | undefined
    */
    sigla?: string | undefined;
    /**
     * @description Percentual do imposto (0-100)
     * @type number | undefined
    */
    percentual?: number | undefined;
    /**
     * @description Status ativo do imposto
     * @type boolean | undefined
    */
    ativo?: boolean | undefined;
};