/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateLocalEstoqueDto = {
    /**
     * @description ID do parceiro proprietário
     * @type number | undefined
    */
    parceiroId?: number | undefined;
    /**
     * @description Nome do local de estoque
     * @type string | undefined
    */
    nome?: string | undefined;
    /**
     * @description Descrição do local de estoque
     * @type string | undefined
    */
    descricao?: string | undefined;
    /**
     * @description Endereço do local de estoque
     * @type string | undefined
    */
    endereco?: string | undefined;
};