/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UsuarioParceiro } from './UsuarioParceiro.ts'

/**
 * @description Lista de relações usuário-parceiro
 */
export type UsuarioParceiroControllerFindAll200 = UsuarioParceiro[]

export type UsuarioParceiroControllerFindAllQueryResponse = UsuarioParceiroControllerFindAll200

export type UsuarioParceiroControllerFindAllQuery = {
  Response: UsuarioParceiroControllerFindAll200
  Errors: any
}
