/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Usuario } from './Usuario.ts'

export type UsuariosControllerFindOnePathParams = {
  /**
   * @description ID público do usuário (UUID v7)
   * @type string
   */
  publicId: string
}

/**
 * @description Usuário encontrado com sucesso
 */
export type UsuariosControllerFindOne200 = Usuario

/**
 * @description Usuário não encontrado
 */
export type UsuariosControllerFindOne404 = any

export type UsuariosControllerFindOneQueryResponse = UsuariosControllerFindOne200

export type UsuariosControllerFindOneQuery = {
  Response: UsuariosControllerFindOne200
  PathParams: UsuariosControllerFindOnePathParams
  Errors: UsuariosControllerFindOne404
}
