/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUsuarioDto } from "./CreateUsuarioDto.ts";
import type { Usuario } from "./Usuario.ts";

/**
 * @description Usuário criado com sucesso
*/
export type UsuariosControllerCreate201 = Usuario;

/**
 * @description Dados de entrada inválidos
*/
export type UsuariosControllerCreate400 = any;

/**
 * @description Email já está em uso
*/
export type UsuariosControllerCreate409 = any;

export type UsuariosControllerCreateMutationRequest = CreateUsuarioDto;

export type UsuariosControllerCreateMutationResponse = UsuariosControllerCreate201;

export type UsuariosControllerCreateMutation = {
    Response: UsuariosControllerCreate201;
    Request: UsuariosControllerCreateMutationRequest;
    Errors: UsuariosControllerCreate400 | UsuariosControllerCreate409;
};