/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VendaItemEntity } from "./VendaItemEntity.ts";

export type VendaItemControllerFindOnePathParams = {
    /**
     * @description ID do item
     * @type string
    */
    id: string;
};

export type VendaItemControllerFindOneQueryParams = {
    /**
     * @type string
    */
    vendaId: string;
};

export type VendaItemControllerFindOneHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Item encontrado
*/
export type VendaItemControllerFindOne200 = VendaItemEntity;

/**
 * @description Item não encontrado
*/
export type VendaItemControllerFindOne404 = any;

export type VendaItemControllerFindOneQueryResponse = VendaItemControllerFindOne200;

export type VendaItemControllerFindOneQuery = {
    Response: VendaItemControllerFindOne200;
    PathParams: VendaItemControllerFindOnePathParams;
    QueryParams: VendaItemControllerFindOneQueryParams;
    HeaderParams: VendaItemControllerFindOneHeaderParams;
    Errors: VendaItemControllerFindOne404;
};