/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Venda } from "./Venda.ts";

export type VendaControllerConfirmarCondicionalPathParams = {
    /**
     * @description ID público da venda
     * @type string
    */
    publicId: string;
};

export type VendaControllerConfirmarCondicionalHeaderParams = {
    /**
     * @description ID do parceiro logado
     * @type integer
    */
    "x-parceiro-id": number;
};

/**
 * @description Condicional confirmada
*/
export type VendaControllerConfirmarCondicional200 = Venda;

export type VendaControllerConfirmarCondicionalMutationResponse = VendaControllerConfirmarCondicional200;

export type VendaControllerConfirmarCondicionalMutation = {
    Response: VendaControllerConfirmarCondicional200;
    PathParams: VendaControllerConfirmarCondicionalPathParams;
    HeaderParams: VendaControllerConfirmarCondicionalHeaderParams;
    Errors: any;
};